<a href="https://colab.research.google.com/github/hyunkyung31/Dajeon_JS/blob/main/hyunkyung/RT_DETR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) bbox → YOLO 포맷 변환 (탐지 공통 준비)     ← 가장 먼저
2) RT-DETR 학습 + test mAP                    ← 메인
3) Swin-T 분류 (frame_df + label)             ← 그다음

Step 1: bbox 있는 keyframe 목록 만들기 (탐지용 데이터 필터링)<br>
Step 2: CADICA bbox → YOLO 포맷([cx,cy,w,h] 정규화) 변환<br>
Step 3: images/labels 폴더 구조 + data.yaml 만들기<br>
Step 4: Ultralytics 설치 + RT-DETR 모델 불러오기<br>
Step 5: 소규모 학습 (몇 epoch 테스트)<br>
Step 6: 결과 확인 (mAP, 예측 bbox 시각화)<br>

 Ultralytics 라이브러리

분류(Swin-T)는 selectedFrames.txt에 있는 keyframe을 다 썼지만, 탐지는 bbox가 있는 프레임만 써야 <br>

groundtruth 폴더 안의 .txt 파일 하나하나가 "bbox 있는 프레임"

In [ ]:
import zipfile
import os

zip_path = '/content/drive/MyDrive/🐥new_2_project/04_DL_project/02_dataset/CADICA.zip'
extract_path = '/content/cadica_dataset/'

if os.path.exists(zip_path) :
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)
    print(f'압축 해제 완료, 저장위치 : {extract_path}')
else :
    print(f'에러 {zip_path}에 파일이 존재하지 않습니다')

압축 해제 완료, 저장위치 : /content/cadica_dataset/

In [ ]:
import pandas as pd
from pathlib import Path

csv_path = "/content/drive/MyDrive/🐥new_2_project/04_DL_project/08_전처리/common_split.csv"
df = pd.read_csv(csv_path)

print(df.shape)
df.head()

(334, 7)

  patient_id video_id       label view  n_frames  has_groundtruth  split
0         p1       v2      lesion  LCA        56             True  train
1         p1       v3      lesion  LCA        44             True  train
2         p1      v10      lesion  LCA        56             True  train
3         p1      v11      lesion  LCA        44             True  train
4         p1       v1  non-lesion  LCA        55            False  train

In [ ]:
# @title Step 1 — bbox 있는 keyframe 목록 만들기

from pathlib import Path
import pandas as pd

base = Path("/content/cadica_dataset/CADICA/selectedVideos")

rows = []
for _, r in df.iterrows():
    gt_dir = base / r.patient_id / r.video_id / "groundtruth"
    if not gt_dir.exists():
        continue  # non-lesion 영상은 groundtruth 폴더 자체가 없음

    for gt_file in sorted(gt_dir.glob("*.txt")):
        if "groundTruthTable" in gt_file.name:  # .mat 관련 텍스트 파일 아님, 확인용
            continue
        frame_id = gt_file.stem  # 예: p1_v2_00015
        img_path = base / r.patient_id / r.video_id / "input" / f"{frame_id}.png"

        rows.append({
            "patient_id": r.patient_id,
            "video_id": r.video_id,
            "frame_id": frame_id,
            "img_path": str(img_path),
            "bbox_path": str(gt_file),
            "split": r.split,
            "view": r.view,
        })

det_df = pd.DataFrame(rows)
print("bbox 있는 프레임 수:", len(det_df))
print(det_df.split.value_counts())
det_df.head()

bbox 있는 프레임 수: 3685
split
train    3077
val       335
test      273
Name: count, dtype: int64

,patient_id,video_id,frame_id,img_path,bbox_path,split,view
0,p1,v2,p1_v2_00015,/content/cadica_dataset/CADICA/selectedVideos/...,/content/cadica_dataset/CADICA/selectedVideos/...,train,<bound method Series.view of patient_id ...
1,p1,v2,p1_v2_00016,/content/cadica_dataset/CADICA/selectedVideos/...,/content/cadica_dataset/CADICA/selectedVideos/...,train,<bound method Series.view of patient_id ...
2,p1,v2,p1_v2_00017,/content/cadica_dataset/CADICA/selectedVideos/...,/content/cadica_dataset/CADICA/selectedVideos/...,train,<bound method Series.view of patient_id ...
3,p1,v2,p1_v2_00018,/content/cadica_dataset/CADICA/selectedVideos/...,/content/cadica_dataset/CADICA/selectedVideos/...,train,<bound method Series.view of patient_id ...
4,p1,v2,p1_v2_00019,/content/cadica_dataset/CADICA/selectedVideos/...,/content/cadica_dataset/CADICA/selectedVideos/...,train,<bound method Series.view of patient_id ...

In [ ]:
det_df["img_exists"] = det_df.img_path.apply(lambda p: Path(p).exists())
det_df["bbox_exists"] = det_df.bbox_path.apply(lambda p: Path(p).exists())
print(det_df.img_exists.value_counts())
print(det_df.bbox_exists.value_counts())

img_exists
True    3685
Name: count, dtype: int64
bbox_exists
True    3685
Name: count, dtype: int64

CADICA groundtruth .txt  
x y w h category

(x, y) = 좌상단 픽셀 좌표<br>
(w, h) = 픽셀 단위 너비/높이<br>
category = p0_20 병변 등급<br>

YOLO/RT-DETR은<br>
class_id cx cy w h<br>
cx, cy, w, h 는 이미지 크기로 나눈 0~1값 <br>
cx, cy는 중심점 <br>

In [ ]:
sample_row = det_df.iloc[0]
print(sample_row.bbox_path)
print(Path(sample_row.bbox_path).read_text())

/content/cadica_dataset/CADICA/selectedVideos/p1/v2/groundtruth/p1_v2_00015.txt
257 123 42 55 p0_20

In [ ]:
import cv2
sample_img = cv2.imread(sample_row.img_path)
print('이미지 크기 (H, W, C):', sample_img.shape)

이미지 크기 (H, W, C): (512, 512, 3)

In [ ]:
# @title bbox 파싱 함수
def parse_bbox_file(bbox_path):
    boxes = []
    with open(bbox_path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split()
            x, y, w, h = map(int, parts[:4])
            category = parts[4] if len(parts) > 4 else "unknown"
            boxes.append({"x": x, "y": y, "w": w, "h": h, "category": category})
    return boxes

# 테스트
boxes = parse_bbox_file(sample_row.bbox_path)
print(boxes)

[{'x': 257, 'y': 123, 'w': 42, 'h': 55, 'category': 'p0_20'}]

In [ ]:
# @title CADICA -> YOLO 좌표 변환 함수

def cadica_to_yolo(x, y, w, h, img_w, img_h):
    cx = (x + w / 2) / img_w
    cy = (y + h / 2) / img_h
    w_norm = w / img_w
    h_norm = h / img_h
    return cx, cy, w_norm, h_norm

# 테스트 (class_id는 지금은 전부 0 = "lesion" 하나로 통일)
img_h, img_w = sample_img.shape[:2]
for b in boxes:
    cx, cy, w_norm, h_norm = cadica_to_yolo(b["x"], b["y"], b["w"], b["h"], img_w, img_h)
    print(f"0 {cx:.6f} {cy:.6f} {w_norm:.6f} {h_norm:.6f}   (원본 category: {b['category']})")

0 0.542969 0.293945 0.082031 0.107422   (원본 category: p0_20)

Ultralytics(YOLOv8, RT-DETR 둘 다 같은 라이브러리)는 학습할 때 이 구조

cadica_yolo/<br>
├── images/<br>
│   ├── train/  (.png 파일들)<br>
│   ├── val/<br>
│   └── test/<br>
├── labels/<br>
│   ├── train/  (.txt 파일들, 이미지와 같은 이름)<br>
│   ├── val/<br>
│   └── test/<br>
└── data.yaml<br>

이미지와 라벨을 같은 파일명(확장자만 다름)으로, 같은 split 폴더에 넣어두면 라이브러리가 자동으로 짝을 맞춰 읽음

In [ ]:
# @title 폴더 만들기
import os

YOLO_ROOT = Path("/content/cadica_yolo")

for split in ["train", "val", "test"]:
    (YOLO_ROOT / "images" / split).mkdir(parents=True, exist_ok=True)
    (YOLO_ROOT / "labels" / split).mkdir(parents=True, exist_ok=True)

print("폴더 생성 완료")
print(list(YOLO_ROOT.rglob("*")))

폴더 생성 완료
[PosixPath('/content/cadica_yolo/labels'), PosixPath('/content/cadica_yolo/images'), PosixPath('/content/cadica_yolo/labels/train'), PosixPath('/content/cadica_yolo/labels/test'), PosixPath('/content/cadica_yolo/labels/val'), PosixPath('/content/cadica_yolo/images/train'), PosixPath('/content/cadica_yolo/images/test'), PosixPath('/content/cadica_yolo/images/val')]

In [ ]:
# @title 이미지 크기를 매번 읽지 않고 캐싱 (속도 최적화)
# 파일별로 직접 확인, cv2.imread 대신 헤더만 읽는 방법

from PIL import Image

def get_image_size_fast(img_path):
    with Image.open(img_path) as im:
        return im.width, im.height  # (W, H)

In [ ]:
# @title  전체 변환 + symlink 생성 함수

import shutil

def process_one_frame(row):
    img_path = Path(row.img_path)
    bbox_path = Path(row.bbox_path)
    split = row.split
    frame_id = row.frame_id

    img_w, img_h = get_image_size_fast(img_path)
    boxes = parse_bbox_file(bbox_path)

    # 라벨(.txt) 생성
    label_lines = []
    for b in boxes:
        cx, cy, w_norm, h_norm = cadica_to_yolo(b["x"], b["y"], b["w"], b["h"], img_w, img_h)
        label_lines.append(f"0 {cx:.6f} {cy:.6f} {w_norm:.6f} {h_norm:.6f}")

    label_out_path = YOLO_ROOT / "labels" / split / f"{frame_id}.txt"
    label_out_path.write_text("\n".join(label_lines))

    # 이미지 symlink 생성
    img_out_path = YOLO_ROOT / "images" / split / f"{frame_id}.png"
    if not img_out_path.exists():
        os.symlink(img_path.resolve(), img_out_path)

    return len(boxes)

In [ ]:
# @title 전체 실행
from tqdm import tqdm

n_boxes_total = 0
errors = []

for _, row in tqdm(det_df.iterrows(), total=len(det_df)):
    try:
        n_boxes = process_one_frame(row)
        n_boxes_total += n_boxes
    except Exception as e:
        errors.append((row.frame_id, str(e)))

print("총 처리된 프레임 수:", len(det_df) - len(errors))
print("총 bbox 수:", n_boxes_total)
print("에러 개수:", len(errors))
if errors:
    print(errors[:5])

100%|██████████| 3685/3685 [00:02<00:00, 1823.62it/s]

총 처리된 프레임 수: 3685
총 bbox 수: 5835
에러 개수: 0

# data.yaml

Ultralytics(RT-DETR, YOLOv8 공통)가 "데이터가 어디 있고, 클래스가 몇 개고, 이름이 뭔지" 알아야 하는 설정

In [ ]:
# @title data.yaml 작성
yaml_content = f"""path: {YOLO_ROOT}
train: images/train
val: images/val
test: images/test

nc: 1
names: ['lesion']
"""

yaml_path = YOLO_ROOT / "data.yaml"
yaml_path.write_text(yaml_content)

print(yaml_path.read_text())

path: /content/cadica_yolo
train: images/train
val: images/val
test: images/test

nc: 1
names: ['lesion']

In [ ]:
# @title 폴더에 실제 파일들이 잘 들어갔는지 확인
for split in ["train", "val", "test"]:
    n_img = len(list((YOLO_ROOT / "images" / split).glob("*.png")))
    n_lbl = len(list((YOLO_ROOT / "labels" / split).glob("*.txt")))
    print(f"{split}: images={n_img}, labels={n_lbl}")

train: images=3077, labels=3077
val: images=335, labels=335
test: images=273, labels=273

In [ ]:
# @title Ultralytics 설치
!pip install -q ultralytics

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.1/42.1 kB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 28.4 MB/s eta 0:00:00

In [ ]:
import ultralytics
ultralytics.checks()

Ultralytics 8.4.95 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 52.6/235.7 GB disk)

Ultralytics는 내부적으로 전부 PyTorch(torch.nn.Module)로 구현

 RT-DETR 모델 불러와서 소규모 학습
 => 일단 소규모로 돌려보고 파이프라인 자체가 문제 없이 돌아가는지 확인하기 위해서 한 에프크 3정도로 실행해보기

In [ ]:
from ultralytics import RTDETR

model = RTDETR("rtdetr-l.pt")  # Ultralytics에서 제공하는 사전학습 가중치
print(model.info())

# rtdetr-l => RT-DETR-Large, COCO로 사전학습된 가중치
# rtdetr-x.pt 가 더 큰 버전

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/rtdetr-l.pt to 'rtdetr-l.pt': 100% ━━━━━━━━━━━━ 63.4MB 86.4MB/s 0.7s
rt-detr-l summary: 449 layers, 32,970,476 parameters, 0 gradients, 108.3 GFLOPs
(449, 32970476, 0, 108.3437056)

In [ ]:
result = model.train(
    data = str(yaml_path),
    epochs = 3,
    imgsz = 640,
    batch = 8,
    device = 0,
    project = '/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result',
    name = 'test_run',
)

Ultralytics 8.4.93 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/cadica_yolo/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dis=6.0, distill_model=None, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=3, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=rtdetr-l.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=test_run, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/test_run, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 107.9MB/s 0.0s
Overriding model.yaml nc=80 with nc=1
WARNING ⚠️ no model scale passed. Assuming scale='l'.

                   from  n    params  module                                       arguments
  0                  -1  1     25248  ultralytics.nn.modules.block.HGStem          [3, 32, 48]
  1                  -1  6    155072  ultralytics.nn.modules.block.HGBlock         [48, 48, 128, 3, 6]
  2                  -1  1      1408  ultralytics.nn.modules.conv.DWConv           [128, 128, 3, 2, 1, False]
  3                  -1  6    839296  ultralytics.nn.modules.block.HGBlock         [128, 96, 512, 3, 6]
  4                  -1  1      5632  ultralytics.nn.modules.conv.DWConv           [512, 512, 3, 2, 1, False]
  5                  -1  6   1695360  ultralytics.nn.modules.block.HGBlock         [512, 192, 1024, 5, 6, True, False]
  6                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  7                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  8                  -1  1     11264  ultralytics.nn.modules.conv.DWConv           [1024, 1024, 3, 2, 1, False]
  9                  -1  6   6708480  ultralytics.nn.modules.block.HGBlock         [1024, 384, 2048, 5, 6, True, False]
 10                  -1  1    524800  ultralytics.nn.modules.conv.Conv             [2048, 256, 1, 1, None, 1, 1, False]
 11                  -1  1    789760  ultralytics.nn.modules.transformer.AIFI      [256, 1024, 8]
 12                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14                   7  1    262656  ultralytics.nn.modules.conv.Conv             [1024, 256, 1, 1, None, 1, 1, False]
 15            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 17                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 18                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 19                   3  1    131584  ultralytics.nn.modules.conv.Conv             [512, 256, 1, 1, None, 1, 1, False]
 20            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 22                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 23            [-1, 17]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 24                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 25                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 26            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 27                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 28        [21, 24, 27]  1   7303907  ultralytics.nn.modules.head.RTDETRDecoder    [1, [256, 256, 256]]
rt-detr-l summary: 465 layers, 32,808,131 parameters, 32,808,131 gradients, 108.0 GFLOPs

Transferred 926/941 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 257.4MB/s 0.0s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1241.7±1337.2 MB/s, size: 102.7 KB)
train: Scanning /content/cadica_yolo/labels/train... 3077 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 3077/3077 1.2Kit/s 2.5s
train: New cache created: /content/cadica_yolo/labels/train.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1013.6±969.3 MB/s, size: 95.2 KB)
val: Scanning /content/cadica_yolo/labels/val... 335 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 335/335 1.3Kit/s 0.3s
val: New cache created: /content/cadica_yolo/labels/val.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.0005), 226 bias(decay=0.0)
Plotting labels to /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/test_run/labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/test_run
Starting training for 3 epochs...

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
        1/3      6.39G      1.695      4.419     0.6414         35        640: 0% ──────────── 0/385  7.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

        1/3      6.56G      1.054      1.168     0.3228          6        640: 100% ━━━━━━━━━━━━ 385/385 1.4it/s 4:29
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 1.7it/s 12.7s
                   all        335        506     0.0966       0.13     0.0369     0.0103

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
        2/3      6.96G     0.7508     0.7425     0.1893         25        640: 0% ──────────── 0/385  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

        2/3      6.96G     0.7548     0.6887      0.199          7        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:12
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 3.0it/s 7.1s
                   all        335        506      0.116      0.083     0.0255    0.00941

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
        3/3      7.01G      1.092     0.6323     0.3202         12        640: 0% ──────────── 0/385  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

        3/3      7.01G     0.6895     0.6827     0.1782         15        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:12
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.3s
                   all        335        506      0.159        0.2      0.077     0.0223

3 epochs completed in 0.226 hours.
Optimizer stripped from /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/test_run/weights/last.pt, 66.3MB
Optimizer stripped from /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/test_run/weights/best.pt, 66.3MB

Validating /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/test_run/weights/best.pt...
Ultralytics 8.4.93 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
rt-detr-l summary: 310 layers, 31,985,795 parameters, 0 gradients, 103.4 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.2it/s 9.4s
                   all        335        506      0.158      0.196     0.0768     0.0224
Speed: 0.3ms preprocess, 21.1ms inference, 0.0ms loss, 0.9ms postprocess per image
Results saved to /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/test_run

Epoch 1/3
전체 3번 중 현재 1번째 <br>
GPU_mem 6.39G
지금 GPU 메모리 6.39GB 사용 중 (T4의 14.9GB 중, 여유 있음)<br>

giou_loss
bbox 위치·크기가 얼마나 정확한지에 대한 손실 (Generalized IoU 기반) — 낮을수록 좋음<br>

cls_loss
bbox 안의 클래스(lesion) 분류가 맞는지에 대한 손실 — 낮을수록 좋음<br>

l1_loss
bbox 좌표의 세부 오차 (또 다른 위치 손실) — 낮을수록 좋음<br>

Instances 35
이번 배치에 있던 bbox 개수<br>

Size 640
입력 이미지 크기

In [ ]:
from ultralytics import RTDETR

model = RTDETR("/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/test_run/weights/best.pt")

results = model.train(
    data=str(yaml_path),
    epochs=50,
    patience=20,       # val mAP 20 epoch 개선 없으면 자동 종료
    imgsz=640,
    batch=8,
    device=0,
    cache=True,         # 2 epoch부터 이미지 로딩 빨라짐
    project="/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result",
    name="train_50ep",
)

Ultralytics 8.4.93 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=True, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/cadica_yolo/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dis=6.0, distill_model=None, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/test_run/weights/best.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=train_50ep-2, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_50ep-2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
WARNING ⚠️ no model scale passed. Assuming scale='l'.

                   from  n    params  module                                       arguments
  0                  -1  1     25248  ultralytics.nn.modules.block.HGStem          [3, 32, 48]
  1                  -1  6    155072  ultralytics.nn.modules.block.HGBlock         [48, 48, 128, 3, 6]
  2                  -1  1      1408  ultralytics.nn.modules.conv.DWConv           [128, 128, 3, 2, 1, False]
  3                  -1  6    839296  ultralytics.nn.modules.block.HGBlock         [128, 96, 512, 3, 6]
  4                  -1  1      5632  ultralytics.nn.modules.conv.DWConv           [512, 512, 3, 2, 1, False]
  5                  -1  6   1695360  ultralytics.nn.modules.block.HGBlock         [512, 192, 1024, 5, 6, True, False]
  6                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  7                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  8                  -1  1     11264  ultralytics.nn.modules.conv.DWConv           [1024, 1024, 3, 2, 1, False]
  9                  -1  6   6708480  ultralytics.nn.modules.block.HGBlock         [1024, 384, 2048, 5, 6, True, False]
 10                  -1  1    524800  ultralytics.nn.modules.conv.Conv             [2048, 256, 1, 1, None, 1, 1, False]
 11                  -1  1    789760  ultralytics.nn.modules.transformer.AIFI      [256, 1024, 8]
 12                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14                   7  1    262656  ultralytics.nn.modules.conv.Conv             [1024, 256, 1, 1, None, 1, 1, False]
 15            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 17                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 18                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 19                   3  1    131584  ultralytics.nn.modules.conv.Conv             [512, 256, 1, 1, None, 1, 1, False]
 20            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 22                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 23            [-1, 17]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 24                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 25                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 26            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 27                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 28        [21, 24, 27]  1   7303907  ultralytics.nn.modules.head.RTDETRDecoder    [1, [256, 256, 256]]
rt-detr-l summary: 465 layers, 32,808,131 parameters, 32,808,131 gradients, 108.0 GFLOPs

Transferred 941/941 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2613.0±945.8 MB/s, size: 99.5 KB)
train: Scanning /content/cadica_yolo/labels/train.cache... 3077 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 3077/3077 921.8Mit/s 0.0s
WARNING ⚠️ train: 5.3GB RAM required to cache images with 50% safety margin but only 4.5/12.7GB available, not caching images
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 461.7±30.3 MB/s, size: 95.7 KB)
val: Scanning /content/cadica_yolo/labels/val.cache... 335 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 335/335 25.1Mit/s 0.0s
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.
val: Caching images (0.4GB RAM): 100% ━━━━━━━━━━━━ 335/335 91.7it/s 3.7s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.0005), 226 bias(decay=0.0)
Plotting labels to /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_50ep-2/labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_50ep-2
Starting training for 50 epochs...

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       1/50      7.18G     0.7055     0.6425     0.1049         35        640: 0% ──────────── 0/385  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       1/50      7.33G     0.6457     0.6056     0.1625          6        640: 100% ━━━━━━━━━━━━ 385/385 1.4it/s 4:27
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.2s
                   all        335        506      0.104      0.166     0.0462     0.0116

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       2/50      6.81G     0.6519     0.5663     0.1618         25        640: 0% ──────────── 0/385  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       2/50      6.81G     0.6669      0.643     0.1721          7        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:23
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.8it/s 7.5s
                   all        335        506      0.114        0.2     0.0595     0.0179

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       3/50      6.86G       0.83     0.6571     0.1703         12        640: 0% ──────────── 0/385  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       3/50      6.86G     0.6745     0.6865     0.1737         15        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:21
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.2s
                   all        335        506     0.0695      0.119     0.0189    0.00565

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       4/50      6.86G     0.5307     0.7454     0.1305         13        640: 0% ──────────── 0/385  0.8s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       4/50      6.86G     0.6778     0.6422     0.1749         19        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:17
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.2s
                   all        335        506      0.138      0.128     0.0506     0.0153

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       5/50      6.86G     0.6653     0.5899     0.1438         23        640: 0% ──────────── 0/385  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       5/50      6.86G     0.6497     0.6188     0.1654         16        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:17
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.2s
                   all        335        506      0.169      0.144      0.056     0.0142

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       6/50      6.86G     0.6683     0.5518     0.1516         29        640: 0% ──────────── 0/385  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       6/50      6.86G      0.652     0.5857     0.1658          9        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:17
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.3s
                   all        335        506      0.186      0.162      0.067     0.0166

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       7/50      6.86G     0.6785     0.5035     0.1315         16        640: 0% ──────────── 0/385  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       7/50      6.86G     0.6346     0.5798     0.1586         20        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:16
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.8it/s 7.4s
                   all        335        506      0.157      0.184     0.0608     0.0157

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       8/50      6.86G     0.5888     0.6904     0.1332         27        640: 0% ──────────── 0/385  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       8/50      6.86G     0.6331     0.5938     0.1606         10        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:15
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.3s
                   all        335        506      0.128      0.148     0.0553     0.0124

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       9/50      6.86G     0.5663     0.6084     0.1114         23        640: 0% ──────────── 0/385  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       9/50      6.86G     0.6055     0.5674     0.1512         11        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:14
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.2s
                   all        335        506      0.151      0.182     0.0593     0.0159

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      10/50      6.86G     0.6776     0.6146     0.1309         18        640: 0% ──────────── 0/385  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      10/50      6.86G     0.5967     0.5534     0.1504         18        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:13
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.4s
                   all        335        506      0.206      0.126      0.108     0.0387

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      11/50      6.86G     0.4423     0.6893     0.1109         10        640: 0% ──────────── 0/385  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      11/50      6.86G     0.5846     0.5469     0.1435          9        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:17
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.8it/s 7.4s
                   all        335        506       0.15      0.184     0.0653     0.0142

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      12/50      6.86G     0.5184     0.5532     0.1158         27        640: 0% ──────────── 0/385  0.9s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      12/50      6.86G     0.5756     0.5316     0.1408         11        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:17
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.2s
                   all        335        506      0.241        0.2      0.111     0.0328

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      13/50      6.86G     0.5118     0.5019     0.1214         17        640: 0% ──────────── 0/385  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      13/50      6.86G      0.565     0.5217       0.14         11        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:22
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 3.0it/s 7.0s
                   all        335        506     0.0936     0.0988     0.0192    0.00363

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      14/50      6.86G     0.5599     0.6672     0.1041         20        640: 0% ──────────── 0/385  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      14/50      6.86G      0.566     0.5273     0.1405         16        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:17
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.2s
                   all        335        506      0.139       0.16     0.0806      0.027

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      15/50      6.86G     0.6162     0.5645     0.1462         19        640: 0% ──────────── 0/385  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      15/50      6.86G     0.5508     0.5117     0.1319         12        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:17
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.3s
                   all        335        506      0.118      0.192      0.052     0.0148

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      16/50      6.86G     0.5657     0.4443     0.1293         21        640: 0% ──────────── 0/385  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      16/50      6.86G     0.5468     0.5068     0.1314          7        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:14
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.2s
                   all        335        506      0.101      0.188     0.0412     0.0104

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      17/50      6.86G     0.7603     0.4738     0.2047         31        640: 0% ──────────── 0/385  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      17/50      6.86G     0.5459     0.4988     0.1315         14        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:16
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.3s
                   all        335        506      0.162      0.142     0.0391     0.0116

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      18/50      6.86G     0.6272     0.4765     0.1242         21        640: 0% ──────────── 0/385  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      18/50      6.86G     0.5379     0.4991     0.1316         20        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:19
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.3s
                   all        335        506      0.174      0.208     0.0885     0.0248

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      19/50      6.86G     0.4687     0.4812    0.09901         22        640: 0% ──────────── 0/385  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      19/50      6.86G     0.5331     0.4829     0.1242         15        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:18
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.8it/s 7.4s
                   all        335        506      0.243      0.206      0.111     0.0268

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      20/50      6.86G     0.7307     0.4925      0.114         20        640: 0% ──────────── 0/385  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      20/50      6.86G     0.5238     0.4747     0.1238         15        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:15
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.8it/s 7.4s
                   all        335        506      0.175      0.148     0.0587     0.0143

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      21/50      6.86G     0.5422      0.581     0.0842         19        640: 0% ──────────── 0/385  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      21/50      6.86G      0.524     0.4874     0.1242         22        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:15
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.4s
                   all        335        506      0.175      0.198      0.064     0.0175

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      22/50      6.86G     0.4642     0.5152      0.146         18        640: 0% ──────────── 0/385  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      22/50      6.86G     0.5183     0.4898     0.1222          8        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:16
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.2s
                   all        335        506      0.122      0.215     0.0537     0.0144

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      23/50      6.86G     0.4596     0.4846    0.09482         20        640: 0% ──────────── 0/385  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      23/50      6.86G     0.5026     0.4697     0.1188         14        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:18
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.3s
                   all        335        506       0.13      0.158     0.0615     0.0182

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      24/50      6.86G     0.5045     0.3951     0.1304         15        640: 0% ──────────── 0/385  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      24/50      6.86G     0.5026     0.4636     0.1171         12        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:14
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.8it/s 7.4s
                   all        335        506      0.197      0.217      0.102     0.0271

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      25/50      6.86G     0.5219     0.4867     0.2067         14        640: 0% ──────────── 0/385  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      25/50      6.86G     0.4881     0.4653     0.1139         16        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:13
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.3s
                   all        335        506      0.268       0.13      0.092     0.0289

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      26/50      6.86G     0.4685     0.4393     0.1053         24        640: 0% ──────────── 0/385  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      26/50      6.86G     0.4993     0.4587     0.1179         11        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:19
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.8it/s 7.5s
                   all        335        506      0.131      0.148     0.0472     0.0113

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      27/50      6.86G     0.5519     0.5662     0.1496         11        640: 0% ──────────── 0/385  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      27/50      6.86G     0.4997     0.4723      0.117          5        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:18
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.8it/s 7.5s
                   all        335        506      0.178       0.16     0.0612     0.0167

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      28/50      6.86G     0.4071     0.4234     0.0916         18        640: 0% ──────────── 0/385  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      28/50      6.86G     0.4792     0.4554      0.113         15        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:16
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.2s
                   all        335        506      0.144       0.18      0.061     0.0153

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      29/50      6.86G     0.3969     0.3913    0.07656         22        640: 0% ──────────── 0/385  0.8s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      29/50      6.86G     0.4724     0.4513     0.1109          5        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:19
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.3s
                   all        335        506        0.2      0.152     0.0698     0.0214

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      30/50      6.86G     0.5223     0.5034     0.1528         19        640: 0% ──────────── 0/385  0.8s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      30/50      6.86G     0.4659     0.4529     0.1085         11        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:19
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.3s
                   all        335        506      0.196      0.101     0.0497      0.016
EarlyStopping: Training stopped early as no improvement observed in last 20 epochs. Best results observed at epoch 10, best model saved as best.pt.
To update EarlyStopping(patience=20) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

30 epochs completed in 2.310 hours.
Optimizer stripped from /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_50ep-2/weights/last.pt, 66.3MB
Optimizer stripped from /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_50ep-2/weights/best.pt, 66.3MB

Validating /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_50ep-2/weights/best.pt...
Ultralytics 8.4.93 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
rt-detr-l summary: 310 layers, 31,985,795 parameters, 0 gradients, 103.4 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.6it/s 8.1s
                   all        335        506      0.208      0.126      0.108      0.039
Speed: 0.3ms preprocess, 18.4ms inference, 0.0ms loss, 0.5ms postprocess per image
Results saved to /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_50ep-2

EarlyStopping: 최근 20 epoch 동안 개선 없음 → epoch 10에서 멈춤<br>
Best model: epoch 10, best.pt<br>
최종 val 성능 (best.pt):<br>
  Precision: 0.208<br>
  Recall:    0.126<br>
  mAP50:     0.108<br>
  mAP50-95:  0.039<br>
총 30 epoch, 2.31시간 소요 (계획한 50 epoch까지 안 가고 자동 멈춤)<br>
best는 epoch 10 — 그 뒤 20 epoch(11~30) 동안 mAP가 이걸 못 넘겼음<br>

loss는 계속 내려가서 학습 자체는 진행되는데, mAP는 실질적인 개선 없음
Recall 0.126으로 병변의 약 87%를 놓침 (임상적으로 부족)
mAP50-95 0.039로 박스 정교함도 낮음

In [ ]:
import numpy as np

bad = []
for _, row in det_df.iterrows():
    boxes = parse_bbox_file(row.bbox_path)
    for b in boxes:
        if b["w"] <= 0 or b["h"] <= 0:
            bad.append((row.frame_id, b))

print("비정상 bbox 개수:", len(bad))
print(bad[:5])

비정상 bbox 개수: 0
[]

In [ ]:
from ultralytics import RTDETR

model = RTDETR("rtdetr-l.pt")  # 이전 체크포인트 아니라 원본 COCO pretrained

results = model.train(
    data=str(yaml_path),
    epochs=50,
    patience=20,
    imgsz=640,
    batch=8,
    device=0,
    cache=True,
    lr0=0.0005,
    optimizer="AdamW",
    amp=False,          # ★ 추가 — mixed precision 끄기 (NaN 방지)
    project="/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result",
    name="train_v3_nofp16",
)

Ultralytics 8.4.93 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=False, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=True, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/cadica_yolo/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dis=6.0, distill_model=None, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.0005, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=rtdetr-l.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=train_v3_nofp16-2, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_v3_nofp16-2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1
WARNING ⚠️ no model scale passed. Assuming scale='l'.

                   from  n    params  module                                       arguments
  0                  -1  1     25248  ultralytics.nn.modules.block.HGStem          [3, 32, 48]
  1                  -1  6    155072  ultralytics.nn.modules.block.HGBlock         [48, 48, 128, 3, 6]
  2                  -1  1      1408  ultralytics.nn.modules.conv.DWConv           [128, 128, 3, 2, 1, False]
  3                  -1  6    839296  ultralytics.nn.modules.block.HGBlock         [128, 96, 512, 3, 6]
  4                  -1  1      5632  ultralytics.nn.modules.conv.DWConv           [512, 512, 3, 2, 1, False]
  5                  -1  6   1695360  ultralytics.nn.modules.block.HGBlock         [512, 192, 1024, 5, 6, True, False]
  6                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  7                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  8                  -1  1     11264  ultralytics.nn.modules.conv.DWConv           [1024, 1024, 3, 2, 1, False]
  9                  -1  6   6708480  ultralytics.nn.modules.block.HGBlock         [1024, 384, 2048, 5, 6, True, False]
 10                  -1  1    524800  ultralytics.nn.modules.conv.Conv             [2048, 256, 1, 1, None, 1, 1, False]
 11                  -1  1    789760  ultralytics.nn.modules.transformer.AIFI      [256, 1024, 8]
 12                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14                   7  1    262656  ultralytics.nn.modules.conv.Conv             [1024, 256, 1, 1, None, 1, 1, False]
 15            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 17                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 18                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 19                   3  1    131584  ultralytics.nn.modules.conv.Conv             [512, 256, 1, 1, None, 1, 1, False]
 20            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 22                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 23            [-1, 17]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 24                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 25                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 26            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 27                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 28        [21, 24, 27]  1   7303907  ultralytics.nn.modules.head.RTDETRDecoder    [1, [256, 256, 256]]
rt-detr-l summary: 465 layers, 32,808,131 parameters, 32,808,131 gradients, 108.0 GFLOPs

Transferred 926/941 items from pretrained weights
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1749.1±465.1 MB/s, size: 99.5 KB)
train: Scanning /content/cadica_yolo/labels/train.cache... 3077 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 3077/3077 717.0Mit/s 0.0s
WARNING ⚠️ train: 5.3GB RAM required to cache images with 50% safety margin but only 3.7/12.7GB available, not caching images
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 883.1±651.0 MB/s, size: 95.7 KB)
val: Scanning /content/cadica_yolo/labels/val.cache... 335 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 335/335 29.9Mit/s 0.0s
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.
val: Caching images (0.4GB RAM): 100% ━━━━━━━━━━━━ 335/335 88.2it/s 3.8s
optimizer: AdamW(lr=0.0005, momentum=0.937) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.0005), 226 bias(decay=0.0)
Plotting labels to /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_v3_nofp16-2/labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_v3_nofp16-2
Starting training for 50 epochs...

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       1/50      9.86G      1.706      4.419     0.6517         35        640: 0% ──────────── 0/385  1.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       1/50      9.86G      1.366     0.5702     0.4461          6        640: 100% ━━━━━━━━━━━━ 385/385 1.3s/it 8:26
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 1.4it/s 15.2s
                   all        335        506    0.00331      0.259    0.00171   0.000419

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       2/50      9.96G     0.9371      0.897     0.2334          7        640: 100% ━━━━━━━━━━━━ 385/385 1.3s/it 8:19
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 1.4it/s 15.0s
                   all        335        506     0.0177      0.265    0.00955     0.0023

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       3/50      10.2G     0.7082       1.07     0.1645         15        640: 100% ━━━━━━━━━━━━ 385/385 1.3s/it 8:18
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 1.4it/s 15.1s
                   all        335        506     0.0324      0.265     0.0244    0.00776

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       4/50      10.1G     0.5965      1.092      0.138         19        640: 100% ━━━━━━━━━━━━ 385/385 1.3s/it 8:17
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 1.4it/s 15.2s
                   all        335        506     0.0533      0.146     0.0276    0.00713

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       5/50      10.1G     0.6016      1.017     0.1431         16        640: 100% ━━━━━━━━━━━━ 385/385 1.3s/it 8:21
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 1.4it/s 15.2s
                   all        335        506     0.0481     0.0929     0.0188    0.00506

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       6/50      10.1G     0.5975     0.9762     0.1415          9        640: 100% ━━━━━━━━━━━━ 385/385 1.3s/it 8:23
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 1.4it/s 15.2s
                   all        335        506     0.0853      0.182      0.035     0.0103

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       7/50      10.1G     0.6363     0.8807     0.1455         21        640: 4% ──────────── 16/385 1.6it/s 21.5s<3:49

KeyboardInterrupt:

In [ ]:
from pathlib import Path
w = Path("/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_v3_nofp16-2/weights")
# 폴더명이 다르면 실제 name으로 바꾸세요
print(list(w.glob("*.pt")) if w.exists() else "경로 확인 필요")

[PosixPath('/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_v3_nofp16-2/weights/last.pt'), PosixPath('/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_v3_nofp16-2/weights/best.pt')]

In [ ]:
from ultralytics import RTDETR

model = RTDETR("/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_v3_nofp16-2/weights/last.pt")
# ↑ 실제 경로로 수정

results = model.train(
    data=str(yaml_path),
    epochs=50,
    patience=20,
    imgsz=640,
    batch=8,
    device=0,
    cache=True,
    lr0=0.0005,
    optimizer="AdamW",
    amp=True,            # ★ 속도 회복
    project="/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result",
    name="train_v3_amp_on",
)

Ultralytics 8.4.93 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=True, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/cadica_yolo/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dis=6.0, distill_model=None, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.0005, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_v3_nofp16-2/weights/last.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=train_v3_amp_on, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_v3_amp_on, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
WARNING ⚠️ no model scale passed. Assuming scale='l'.

                   from  n    params  module                                       arguments
  0                  -1  1     25248  ultralytics.nn.modules.block.HGStem          [3, 32, 48]
  1                  -1  6    155072  ultralytics.nn.modules.block.HGBlock         [48, 48, 128, 3, 6]
  2                  -1  1      1408  ultralytics.nn.modules.conv.DWConv           [128, 128, 3, 2, 1, False]
  3                  -1  6    839296  ultralytics.nn.modules.block.HGBlock         [128, 96, 512, 3, 6]
  4                  -1  1      5632  ultralytics.nn.modules.conv.DWConv           [512, 512, 3, 2, 1, False]
  5                  -1  6   1695360  ultralytics.nn.modules.block.HGBlock         [512, 192, 1024, 5, 6, True, False]
  6                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  7                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  8                  -1  1     11264  ultralytics.nn.modules.conv.DWConv           [1024, 1024, 3, 2, 1, False]
  9                  -1  6   6708480  ultralytics.nn.modules.block.HGBlock         [1024, 384, 2048, 5, 6, True, False]
 10                  -1  1    524800  ultralytics.nn.modules.conv.Conv             [2048, 256, 1, 1, None, 1, 1, False]
 11                  -1  1    789760  ultralytics.nn.modules.transformer.AIFI      [256, 1024, 8]
 12                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14                   7  1    262656  ultralytics.nn.modules.conv.Conv             [1024, 256, 1, 1, None, 1, 1, False]
 15            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 17                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 18                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 19                   3  1    131584  ultralytics.nn.modules.conv.Conv             [512, 256, 1, 1, None, 1, 1, False]
 20            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 22                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 23            [-1, 17]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 24                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 25                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 26            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 27                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 28        [21, 24, 27]  1   7303907  ultralytics.nn.modules.head.RTDETRDecoder    [1, [256, 256, 256]]
rt-detr-l summary: 465 layers, 32,808,131 parameters, 32,808,131 gradients, 108.0 GFLOPs

Transferred 941/941 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
WARNING ⚠️ train: Slow image access detected (ping: 0.0±0.0 ms, read: 45.9±13.0 MB/s, size: 99.5 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
train: Scanning /content/cadica_yolo/labels/train.cache... 3077 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 3077/3077 586.6Mit/s 0.0s
WARNING ⚠️ train: 5.3GB RAM required to cache images with 50% safety margin but only 3.0/12.7GB available, not caching images
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
WARNING ⚠️ val: Slow image access detected (ping: 0.0±0.0 ms, read: 36.2±21.2 MB/s, size: 95.7 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
val: Scanning /content/cadica_yolo/labels/val.cache... 335 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 335/335 28.7Mit/s 0.0s
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.
val: Caching images (0.4GB RAM): 100% ━━━━━━━━━━━━ 335/335 117.4it/s 2.9s
optimizer: AdamW(lr=0.0005, momentum=0.937) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.0005), 226 bias(decay=0.0)
Plotting labels to /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_v3_amp_on/labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_v3_amp_on
Starting training for 50 epochs...

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       1/50      10.1G     0.6739     0.8694     0.1346         35        640: 0% ──────────── 0/385  0.9s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       1/50      10.1G     0.8647     0.7768     0.2112          6        640: 100% ━━━━━━━━━━━━ 385/385 1.4it/s 4:30
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.3s
                   all        335        506      0.111      0.117     0.0232    0.00609

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       2/50      6.64G     0.9896     0.6455     0.1643         25        640: 0% ──────────── 0/385  2.0s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       2/50      6.64G     0.7535     0.7027     0.1804          7        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:19
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.2s
                   all        335        506      0.203      0.237     0.0893     0.0223

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       3/50      6.69G     0.9696     0.4744     0.2082         12        640: 0% ──────────── 0/385  1.8s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       3/50      6.69G     0.7008     0.7933     0.1675         15        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:14
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 3.0it/s 7.1s
                   all        335        506      0.197      0.239     0.0921     0.0207

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       4/50      6.69G      0.601     0.5928     0.1711         13        640: 0% ──────────── 0/385  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       4/50      6.69G     0.6627     0.6703     0.1665         19        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:16
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 3.0it/s 7.1s
                   all        335        506      0.113     0.0889     0.0334    0.00711

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       5/50      6.69G     0.6678     0.5902      0.141         23        640: 0% ──────────── 0/385  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       5/50      6.69G     0.5961     0.7553     0.1453         16        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:15
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.2s
                   all        335        506      0.144     0.0711     0.0282     0.0073

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       6/50      6.69G     0.6802     0.6618     0.1646         29        640: 0% ──────────── 0/385  1.1s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       6/50      6.69G     0.6137      0.697     0.1495          9        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:13
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 3.0it/s 7.1s
                   all        335        506       0.16       0.15     0.0817     0.0204

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       7/50      6.69G      0.698     0.7118     0.1295         16        640: 0% ──────────── 0/385  0.8s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       7/50      6.69G     0.6073       0.71     0.1457         20        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:14
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 3.0it/s 7.0s
                   all        335        506      0.188       0.13     0.0548     0.0133

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       8/50      6.69G     0.6667     0.6741     0.1808         27        640: 0% ──────────── 0/385  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       8/50      6.69G     0.6329     0.7067     0.1589         10        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:13
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 3.0it/s 7.1s
                   all        335        506      0.121      0.158     0.0605     0.0165

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       9/50      6.69G     0.5906     0.6401     0.1157         23        640: 0% ──────────── 0/385  1.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       9/50      6.69G      0.585     0.6675     0.1418         11        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:13
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.2s
                   all        335        506      0.156      0.172     0.0621     0.0146

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      10/50      6.69G     0.6934     0.6996     0.1282         18        640: 0% ──────────── 0/385  0.9s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      10/50      6.69G     0.5998     0.6311      0.147         18        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:12
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.2s
                   all        335        506      0.127      0.125     0.0334    0.00877

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      11/50      6.69G     0.5619     0.7646     0.1569         10        640: 0% ──────────── 0/385  1.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      11/50      6.69G     0.5822     0.5901     0.1425          9        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:16
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.1s
                   all        335        506      0.228      0.225      0.118     0.0305

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      12/50      6.69G     0.5894     0.5096     0.1262         27        640: 0% ──────────── 0/385  1.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      12/50      6.69G     0.5712     0.5854     0.1369         11        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:10
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.2s
                   all        335        506      0.257       0.19     0.0837     0.0188

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      13/50      6.69G      0.587     0.6571     0.1546         17        640: 0% ──────────── 0/385  0.9s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      13/50      6.69G     0.5572     0.6114     0.1347         11        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:12
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.3s
                   all        335        506      0.221      0.172     0.0896     0.0203

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      14/50      6.69G     0.6281     0.5859     0.1281         20        640: 0% ──────────── 0/385  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      14/50      6.69G     0.5483     0.5525     0.1313         16        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:13
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.3s
                   all        335        506       0.16      0.176     0.0684     0.0186

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      15/50      6.69G     0.7353     0.5087     0.1489         19        640: 0% ──────────── 0/385  1.1s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      15/50      6.69G     0.5415     0.5609     0.1256         12        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:10
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 3.0it/s 7.0s
                   all        335        506     0.0998      0.164     0.0474     0.0121

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      16/50      6.69G     0.4973     0.4976     0.1206         21        640: 0% ──────────── 0/385  1.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      16/50      6.69G     0.5298     0.5328     0.1244          7        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:12
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.2s
                   all        335        506      0.158      0.136     0.0607     0.0139

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      17/50      6.69G     0.7109     0.5723     0.1677         31        640: 0% ──────────── 0/385  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      17/50      6.69G     0.5322     0.5283     0.1258         14        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:14
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.2s
                   all        335        506       0.18      0.142     0.0529     0.0108

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      18/50      6.69G     0.5536     0.5833    0.09438         21        640: 0% ──────────── 0/385  1.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      18/50      6.69G     0.5165     0.5211      0.122         20        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:13
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 3.0it/s 7.0s
                   all        335        506      0.244      0.174      0.093     0.0204

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      19/50      6.69G     0.4279     0.4545    0.08357         22        640: 0% ──────────── 0/385  1.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      19/50      6.69G     0.5125     0.5009     0.1179         15        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:12
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 3.0it/s 7.0s
                   all        335        506      0.122      0.164     0.0576     0.0142

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      20/50      6.69G     0.6895     0.5147    0.09589         20        640: 0% ──────────── 0/385  0.9s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      20/50      6.69G     0.5051     0.4972     0.1174         15        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:14
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.2s
                   all        335        506      0.145       0.14     0.0498      0.012

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      21/50      6.69G     0.5335     0.4837    0.09343         19        640: 0% ──────────── 0/385  1.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      21/50      6.69G     0.5097       0.48     0.1185         22        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:16
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.2s
                   all        335        506      0.115      0.178     0.0408    0.00942

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      22/50      6.69G     0.4594     0.5206     0.1315         18        640: 0% ──────────── 0/385  1.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      22/50      6.69G     0.5045     0.4787     0.1175          8        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:12
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.2s
                   all        335        506      0.236      0.192     0.0859     0.0186

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      23/50      6.69G     0.5125     0.4488     0.1107         20        640: 0% ──────────── 0/385  1.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      23/50      6.69G     0.4894     0.4791     0.1145         14        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:12
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.3s
                   all        335        506      0.155      0.213     0.0916     0.0246

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      24/50      6.69G     0.4407     0.4264     0.1014         15        640: 0% ──────────── 0/385  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      24/50      6.69G     0.4842     0.4701     0.1098         12        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:24
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.3s
                   all        335        506      0.143      0.162     0.0573     0.0145

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      25/50      6.69G     0.4363     0.4824     0.1632         14        640: 0% ──────────── 0/385  1.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      25/50      6.69G     0.4803     0.4732      0.111         16        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:24
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 3.0it/s 7.1s
                   all        335        506      0.171      0.154     0.0691     0.0185

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      26/50      6.69G      0.528     0.4098     0.1103         24        640: 0% ──────────── 0/385  1.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      26/50      6.69G     0.4794     0.4603     0.1103         11        640: 100% ━━━━━━━━━━━━ 385/385 1.4it/s 4:26
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.3s
                   all        335        506      0.128      0.144     0.0452     0.0102

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      27/50      6.69G     0.5848     0.4349     0.1629         11        640: 0% ──────────── 0/385  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      27/50      6.69G     0.4798     0.4715     0.1098          5        640: 100% ━━━━━━━━━━━━ 385/385 1.4it/s 4:28
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 3.0it/s 7.0s
                   all        335        506      0.174       0.13     0.0644       0.02

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      28/50      6.69G     0.4268     0.4259    0.08445         18        640: 0% ──────────── 0/385  1.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      28/50      6.69G     0.4666     0.4574     0.1079         15        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:25
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.2s
                   all        335        506      0.208      0.194       0.09      0.019

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      29/50      6.69G     0.4796      0.421    0.09893         22        640: 0% ──────────── 0/385  0.9s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      29/50      6.69G     0.4725     0.4538     0.1084          5        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:24
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.2s
                   all        335        506      0.232      0.186     0.0809     0.0173

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      30/50      6.69G     0.3963      0.445     0.1116         19        640: 0% ──────────── 0/385  1.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      30/50      6.69G     0.4506     0.4486     0.1034         11        640: 100% ━━━━━━━━━━━━ 385/385 1.5it/s 4:25
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 3.0it/s 7.0s
                   all        335        506      0.134       0.16     0.0469      0.011

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      31/50      6.69G     0.4511     0.4515     0.1056         10        640: 100% ━━━━━━━━━━━━ 385/385 1.4it/s 4:26
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 2.9it/s 7.2s
                   all        335        506      0.194      0.204     0.0771      0.018
EarlyStopping: Training stopped early as no improvement observed in last 20 epochs. Best results observed at epoch 11, best model saved as best.pt.
To update EarlyStopping(patience=20) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

31 epochs completed in 2.741 hours.
Optimizer stripped from /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_v3_amp_on/weights/last.pt, 66.3MB
Optimizer stripped from /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_v3_amp_on/weights/best.pt, 66.3MB

Validating /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_v3_amp_on/weights/best.pt...
Ultralytics 8.4.93 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
rt-detr-l summary: 310 layers, 31,985,795 parameters, 0 gradients, 103.4 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 4% ╸─────────── 1/21 1.9s/it 0.6s<37.4s

- EarlyStopping @ epoch 11 (patience=20, 31 epoch까지 돌고 종료)
- Best (ep11): P=0.228, R=0.225, mAP50=0.118, mAP50-95=0.0305
- 이전 런(ep10, mAP50=0.108)보다 살짝 개선 → 현재까지 best.pt 기준

In [ ]:
# @title best.pt로 val + test 평가
from ultralytics import RTDETR

BEST = "/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_v3_amp_on/weights/best.pt"
model = RTDETR(BEST)

val = model.val(data="/content/cadica_yolo/data.yaml", split="val", imgsz=640, batch=8)
test = model.val(data="/content/cadica_yolo/data.yaml", split="test", imgsz=640, batch=8)

print(f"VAL  P={val.box.mp:.3f} R={val.box.mr:.3f} mAP50={val.box.map50:.3f} mAP50-95={val.box.map:.3f}")
print(f"TEST P={test.box.mp:.3f} R={test.box.mr:.3f} mAP50={test.box.map50:.3f} mAP50-95={test.box.map:.3f}")

Ultralytics 8.4.95 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
rt-detr-l summary: 310 layers, 31,985,795 parameters, 0 gradients, 103.4 GFLOPs
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 22.5MB/s 0.0s
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2424.9±632.3 MB/s, size: 95.5 KB)
val: Scanning /content/cadica_yolo/labels/val... 335 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 335/335 1.6Kit/s 0.2s
val: New cache created: /content/cadica_yolo/labels/val.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 2.9it/s 14.5s
                   all        335        506      0.229      0.219      0.117       0.03
Speed: 1.5ms preprocess, 33.8ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to /content/runs/detect/val
Ultralytics 8.4.95 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
rt-detr-l summary: 310 layers, 31,985,795 parameters, 0 gradients, 103.4 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2223.2±1249.2 MB/s, size: 102.1 KB)
val: Scanning /content/cadica_yolo/labels/test... 273 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 273/273 1.6Kit/s 0.2s
val: New cache created: /content/cadica_yolo/labels/test.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 35/35 3.3it/s 10.6s
                   all        273        273      0.592      0.289      0.308       0.15
Speed: 1.4ms preprocess, 33.8ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to /content/runs/detect/val-2
VAL  P=0.229 R=0.219 mAP50=0.117 mAP50-95=0.030
TEST P=0.592 R=0.289 mAP50=0.308 mAP50-95=0.150

In [ ]:
# @title qualitative
model.predict(
    source="/content/cadica_yolo/images/test",
    conf=0.25, imgsz=640, save=True,
    project="/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result",
    name="predict_test_v3"
)

image 1/273 /content/cadica_yolo/images/test/p28_v6_00013.png: 640x640 1 lesion, 72.3ms
image 2/273 /content/cadica_yolo/images/test/p28_v6_00014.png: 640x640 2 lesions, 69.7ms
image 3/273 /content/cadica_yolo/images/test/p28_v6_00015.png: 640x640 3 lesions, 70.3ms
image 4/273 /content/cadica_yolo/images/test/p28_v6_00020.png: 640x640 1 lesion, 69.4ms
image 5/273 /content/cadica_yolo/images/test/p28_v6_00021.png: 640x640 1 lesion, 55.9ms
image 6/273 /content/cadica_yolo/images/test/p28_v6_00022.png: 640x640 2 lesions, 55.4ms
image 7/273 /content/cadica_yolo/images/test/p28_v6_00025.png: 640x640 2 lesions, 54.2ms
image 8/273 /content/cadica_yolo/images/test/p28_v6_00028.png: 640x640 1 lesion, 56.0ms
image 9/273 /content/cadica_yolo/images/test/p28_v6_00029.png: 640x640 2 lesions, 55.5ms
image 10/273 /content/cadica_yolo/images/test/p28_v6_00030.png: 640x640 1 lesion, 51.4ms
image 11/273 /content/cadica_yolo/images/test/p28_v7_00023.png: 640x640 1 lesion, 52.3ms
image 12/273 /content/cadica_yolo/images/test/p28_v7_00024.png: 640x640 2 lesions, 50.0ms
image 13/273 /content/cadica_yolo/images/test/p28_v7_00025.png: 640x640 1 lesion, 52.3ms
image 14/273 /content/cadica_yolo/images/test/p28_v7_00026.png: 640x640 1 lesion, 50.6ms
image 15/273 /content/cadica_yolo/images/test/p28_v7_00027.png: 640x640 3 lesions, 48.2ms
image 16/273 /content/cadica_yolo/images/test/p28_v7_00028.png: 640x640 2 lesions, 48.6ms
image 17/273 /content/cadica_yolo/images/test/p28_v7_00029.png: 640x640 3 lesions, 49.9ms
image 18/273 /content/cadica_yolo/images/test/p28_v7_00030.png: 640x640 1 lesion, 47.9ms
image 19/273 /content/cadica_yolo/images/test/p28_v7_00031.png: 640x640 1 lesion, 51.1ms
image 20/273 /content/cadica_yolo/images/test/p28_v7_00032.png: 640x640 (no detections), 48.2ms
image 21/273 /content/cadica_yolo/images/test/p28_v7_00033.png: 640x640 1 lesion, 57.7ms
image 22/273 /content/cadica_yolo/images/test/p28_v8_00014.png: 640x640 2 lesions, 47.7ms
image 23/273 /content/cadica_yolo/images/test/p28_v8_00017.png: 640x640 1 lesion, 48.0ms
image 24/273 /content/cadica_yolo/images/test/p28_v8_00018.png: 640x640 2 lesions, 58.3ms
image 25/273 /content/cadica_yolo/images/test/p28_v8_00019.png: 640x640 1 lesion, 48.2ms
image 26/273 /content/cadica_yolo/images/test/p28_v8_00020.png: 640x640 2 lesions, 50.0ms
image 27/273 /content/cadica_yolo/images/test/p28_v8_00021.png: 640x640 (no detections), 48.9ms
image 28/273 /content/cadica_yolo/images/test/p28_v8_00022.png: 640x640 2 lesions, 48.3ms
image 29/273 /content/cadica_yolo/images/test/p28_v8_00024.png: 640x640 2 lesions, 50.0ms
image 30/273 /content/cadica_yolo/images/test/p28_v8_00025.png: 640x640 2 lesions, 47.1ms
image 31/273 /content/cadica_yolo/images/test/p28_v8_00026.png: 640x640 1 lesion, 47.7ms
image 32/273 /content/cadica_yolo/images/test/p28_v8_00027.png: 640x640 1 lesion, 47.4ms
image 33/273 /content/cadica_yolo/images/test/p28_v8_00028.png: 640x640 1 lesion, 47.7ms
image 34/273 /content/cadica_yolo/images/test/p30_v1_00013.png: 640x640 3 lesions, 48.4ms
image 35/273 /content/cadica_yolo/images/test/p30_v1_00014.png: 640x640 1 lesion, 51.7ms
image 36/273 /content/cadica_yolo/images/test/p30_v1_00015.png: 640x640 2 lesions, 47.1ms
image 37/273 /content/cadica_yolo/images/test/p30_v1_00016.png: 640x640 1 lesion, 50.1ms
image 38/273 /content/cadica_yolo/images/test/p30_v1_00018.png: 640x640 4 lesions, 47.8ms
image 39/273 /content/cadica_yolo/images/test/p30_v1_00020.png: 640x640 3 lesions, 46.8ms
image 40/273 /content/cadica_yolo/images/test/p30_v2_00011.png: 640x640 4 lesions, 47.4ms
image 41/273 /content/cadica_yolo/images/test/p30_v2_00012.png: 640x640 1 lesion, 65.4ms
image 42/273 /content/cadica_yolo/images/test/p30_v2_00013.png: 640x640 1 lesion, 47.2ms
image 43/273 /content/cadica_yolo/images/test/p30_v2_00014.png: 640x640 3 lesions, 50.7ms
image 44/273 /content/cadica_yolo/images/test/p30_v2_00015.png: 640x640 1 lesion, 47.5ms
image 45/273 /content/cadica_yolo/images/test/p30_v2_00016.png: 640x640 1 lesion, 48.2ms
image 46/273 /content/cadica_yolo/images/test/p30_v2_00017.png: 640x640 2 lesions, 50.1ms
image 47/273 /content/cadica_yolo/images/test/p30_v2_00018.png: 640x640 3 lesions, 51.2ms
image 48/273 /content/cadica_yolo/images/test/p30_v2_00019.png: 640x640 2 lesions, 49.3ms
image 49/273 /content/cadica_yolo/images/test/p30_v2_00020.png: 640x640 1 lesion, 50.8ms
image 50/273 /content/cadica_yolo/images/test/p30_v2_00021.png: 640x640 1 lesion, 50.1ms
image 51/273 /content/cadica_yolo/images/test/p30_v2_00022.png: 640x640 2 lesions, 49.4ms
image 52/273 /content/cadica_yolo/images/test/p30_v2_00023.png: 640x640 1 lesion, 49.9ms
image 53/273 /content/cadica_yolo/images/test/p30_v2_00024.png: 640x640 1 lesion, 50.5ms
image 54/273 /content/cadica_yolo/images/test/p30_v2_00025.png: 640x640 1 lesion, 48.0ms
image 55/273 /content/cadica_yolo/images/test/p30_v2_00026.png: 640x640 1 lesion, 57.6ms
image 56/273 /content/cadica_yolo/images/test/p30_v2_00027.png: 640x640 2 lesions, 47.2ms
image 57/273 /content/cadica_yolo/images/test/p30_v2_00028.png: 640x640 4 lesions, 48.2ms
image 58/273 /content/cadica_yolo/images/test/p30_v2_00029.png: 640x640 3 lesions, 47.3ms
image 59/273 /content/cadica_yolo/images/test/p30_v3_00010.png: 640x640 1 lesion, 49.0ms
image 60/273 /content/cadica_yolo/images/test/p30_v3_00011.png: 640x640 1 lesion, 47.7ms
image 61/273 /content/cadica_yolo/images/test/p30_v3_00012.png: 640x640 2 lesions, 47.6ms
image 62/273 /content/cadica_yolo/images/test/p30_v3_00013.png: 640x640 1 lesion, 49.8ms
image 63/273 /content/cadica_yolo/images/test/p30_v3_00014.png: 640x640 1 lesion, 49.3ms
image 64/273 /content/cadica_yolo/images/test/p30_v3_00015.png: 640x640 3 lesions, 48.0ms
image 65/273 /content/cadica_yolo/images/test/p30_v3_00016.png: 640x640 1 lesion, 49.2ms
image 66/273 /content/cadica_yolo/images/test/p30_v3_00017.png: 640x640 1 lesion, 48.3ms
image 67/273 /content/cadica_yolo/images/test/p30_v3_00018.png: 640x640 2 lesions, 47.9ms
image 68/273 /content/cadica_yolo/images/test/p30_v3_00019.png: 640x640 2 lesions, 60.4ms
image 69/273 /content/cadica_yolo/images/test/p30_v3_00020.png: 640x640 1 lesion, 47.3ms
image 70/273 /content/cadica_yolo/images/test/p30_v3_00021.png: 640x640 2 lesions, 47.9ms
image 71/273 /content/cadica_yolo/images/test/p30_v3_00022.png: 640x640 1 lesion, 48.3ms
image 72/273 /content/cadica_yolo/images/test/p30_v3_00023.png: 640x640 1 lesion, 48.4ms
image 73/273 /content/cadica_yolo/images/test/p30_v3_00024.png: 640x640 2 lesions, 48.0ms
image 74/273 /content/cadica_yolo/images/test/p30_v3_00025.png: 640x640 2 lesions, 50.0ms
image 75/273 /content/cadica_yolo/images/test/p30_v3_00026.png: 640x640 1 lesion, 54.3ms
image 76/273 /content/cadica_yolo/images/test/p30_v3_00027.png: 640x640 2 lesions, 48.2ms
image 77/273 /content/cadica_yolo/images/test/p30_v3_00028.png: 640x640 2 lesions, 47.8ms
image 78/273 /content/cadica_yolo/images/test/p30_v3_00029.png: 640x640 2 lesions, 49.0ms
image 79/273 /content/cadica_yolo/images/test/p30_v3_00030.png: 640x640 3 lesions, 50.0ms
image 80/273 /content/cadica_yolo/images/test/p30_v6_00018.png: 640x640 2 lesions, 50.2ms
image 81/273 /content/cadica_yolo/images/test/p30_v7_00012.png: 640x640 1 lesion, 47.0ms
image 82/273 /content/cadica_yolo/images/test/p30_v7_00013.png: 640x640 1 lesion, 62.3ms
image 83/273 /content/cadica_yolo/images/test/p30_v7_00014.png: 640x640 1 lesion, 49.7ms
image 84/273 /content/cadica_yolo/images/test/p30_v7_00015.png: 640x640 3 lesions, 52.6ms
image 85/273 /content/cadica_yolo/images/test/p30_v7_00016.png: 640x640 2 lesions, 47.8ms
image 86/273 /content/cadica_yolo/images/test/p30_v7_00017.png: 640x640 1 lesion, 47.5ms
image 87/273 /content/cadica_yolo/images/test/p30_v7_00018.png: 640x640 2 lesions, 52.1ms
image 88/273 /content/cadica_yolo/images/test/p30_v7_00019.png: 640x640 1 lesion, 59.3ms
image 89/273 /content/cadica_yolo/images/test/p30_v7_00020.png: 640x640 2 lesions, 49.6ms
image 90/273 /content/cadica_yolo/images/test/p30_v7_00021.png: 640x640 2 lesions, 58.6ms
image 91/273 /content/cadica_yolo/images/test/p30_v7_00022.png: 640x640 1 lesion, 48.2ms
image 92/273 /content/cadica_yolo/images/test/p30_v7_00023.png: 640x640 2 lesions, 50.7ms
image 93/273 /content/cadica_yolo/images/test/p30_v7_00024.png: 640x640 4 lesions, 51.5ms
image 94/273 /content/cadica_yolo/images/test/p30_v7_00025.png: 640x640 2 lesions, 47.5ms
image 95/273 /content/cadica_yolo/images/test/p38_v1_00015.png: 640x640 (no detections), 47.9ms
image 96/273 /content/cadica_yolo/images/test/p38_v1_00016.png: 640x640 (no detections), 51.9ms
image 97/273 /content/cadica_yolo/images/test/p38_v1_00017.png: 640x640 (no detections), 56.6ms
image 98/273 /content/cadica_yolo/images/test/p38_v1_00018.png: 640x640 (no detections), 47.1ms
image 99/273 /content/cadica_yolo/images/test/p38_v1_00019.png: 640x640 (no detections), 57.7ms
image 100/273 /content/cadica_yolo/images/test/p38_v1_00020.png: 640x640 (no detections), 48.5ms
image 101/273 /content/cadica_yolo/images/test/p38_v1_00021.png: 640x640 (no detections), 47.5ms
image 102/273 /content/cadica_yolo/images/test/p38_v1_00022.png: 640x640 (no detections), 47.8ms
image 103/273 /content/cadica_yolo/images/test/p38_v1_00023.png: 640x640 (no detections), 46.7ms
image 104/273 /content/cadica_yolo/images/test/p38_v1_00024.png: 640x640 (no detections), 49.6ms
image 105/273 /content/cadica_yolo/images/test/p38_v1_00025.png: 640x640 (no detections), 47.5ms
image 106/273 /content/cadica_yolo/images/test/p38_v1_00026.png: 640x640 1 lesion, 47.6ms
image 107/273 /content/cadica_yolo/images/test/p38_v1_00027.png: 640x640 (no detections), 47.3ms
image 108/273 /content/cadica_yolo/images/test/p38_v1_00028.png: 640x640 (no detections), 47.9ms
image 109/273 /content/cadica_yolo/images/test/p38_v1_00029.png: 640x640 (no detections), 57.6ms
image 110/273 /content/cadica_yolo/images/test/p38_v1_00030.png: 640x640 (no detections), 67.4ms
image 111/273 /content/cadica_yolo/images/test/p38_v1_00031.png: 640x640 (no detections), 48.0ms
image 112/273 /content/cadica_yolo/images/test/p38_v1_00032.png: 640x640 (no detections), 50.6ms
image 113/273 /content/cadica_yolo/images/test/p38_v1_00033.png: 640x640 (no detections), 48.1ms
image 114/273 /content/cadica_yolo/images/test/p38_v1_00034.png: 640x640 (no detections), 49.3ms
image 115/273 /content/cadica_yolo/images/test/p38_v2_00019.png: 640x640 3 lesions, 52.2ms
image 116/273 /content/cadica_yolo/images/test/p38_v2_00020.png: 640x640 2 lesions, 48.6ms
image 117/273 /content/cadica_yolo/images/test/p38_v2_00021.png: 640x640 1 lesion, 48.7ms
image 118/273 /content/cadica_yolo/images/test/p38_v2_00023.png: 640x640 2 lesions, 48.6ms
image 119/273 /content/cadica_yolo/images/test/p38_v2_00024.png: 640x640 1 lesion, 47.4ms
image 120/273 /content/cadica_yolo/images/test/p38_v2_00025.png: 640x640 2 lesions, 74.3ms
image 121/273 /content/cadica_yolo/images/test/p38_v2_00026.png: 640x640 2 lesions, 79.3ms
image 122/273 /content/cadica_yolo/images/test/p38_v8_00018.png: 640x640 2 lesions, 75.0ms
image 123/273 /content/cadica_yolo/images/test/p38_v8_00019.png: 640x640 3 lesions, 81.7ms
image 124/273 /content/cadica_yolo/images/test/p38_v8_00020.png: 640x640 4 lesions, 69.4ms
image 125/273 /content/cadica_yolo/images/test/p38_v8_00021.png: 640x640 2 lesions, 69.2ms
image 126/273 /content/cadica_yolo/images/test/p38_v8_00022.png: 640x640 3 lesions, 73.4ms
image 127/273 /content/cadica_yolo/images/test/p38_v8_00023.png: 640x640 2 lesions, 70.1ms
image 128/273 /content/cadica_yolo/images/test/p38_v8_00024.png: 640x640 2 lesions, 71.0ms
image 129/273 /content/cadica_yolo/images/test/p38_v8_00025.png: 640x640 2 lesions, 68.7ms
image 130/273 /content/cadica_yolo/images/test/p38_v8_00026.png: 640x640 2 lesions, 71.7ms
image 131/273 /content/cadica_yolo/images/test/p38_v8_00027.png: 640x640 4 lesions, 69.8ms
image 132/273 /content/cadica_yolo/images/test/p38_v8_00028.png: 640x640 2 lesions, 71.2ms
image 133/273 /content/cadica_yolo/images/test/p38_v8_00029.png: 640x640 4 lesions, 72.3ms
image 134/273 /content/cadica_yolo/images/test/p38_v8_00033.png: 640x640 3 lesions, 69.5ms
image 135/273 /content/cadica_yolo/images/test/p38_v9_00015.png: 640x640 1 lesion, 79.0ms
image 136/273 /content/cadica_yolo/images/test/p38_v9_00016.png: 640x640 1 lesion, 91.9ms
image 137/273 /content/cadica_yolo/images/test/p38_v9_00017.png: 640x640 (no detections), 73.8ms
image 138/273 /content/cadica_yolo/images/test/p38_v9_00018.png: 640x640 1 lesion, 72.8ms
image 139/273 /content/cadica_yolo/images/test/p38_v9_00019.png: 640x640 1 lesion, 72.1ms
image 140/273 /content/cadica_yolo/images/test/p38_v9_00020.png: 640x640 (no detections), 75.5ms
image 141/273 /content/cadica_yolo/images/test/p38_v9_00021.png: 640x640 (no detections), 71.8ms
image 142/273 /content/cadica_yolo/images/test/p38_v9_00022.png: 640x640 1 lesion, 72.5ms
image 143/273 /content/cadica_yolo/images/test/p38_v9_00023.png: 640x640 1 lesion, 72.4ms
image 144/273 /content/cadica_yolo/images/test/p38_v9_00024.png: 640x640 1 lesion, 75.3ms
image 145/273 /content/cadica_yolo/images/test/p38_v9_00025.png: 640x640 (no detections), 73.0ms
image 146/273 /content/cadica_yolo/images/test/p38_v9_00026.png: 640x640 1 lesion, 75.6ms
image 147/273 /content/cadica_yolo/images/test/p38_v9_00027.png: 640x640 1 lesion, 78.2ms
image 148/273 /content/cadica_yolo/images/test/p38_v9_00028.png: 640x640 1 lesion, 73.6ms
image 149/273 /content/cadica_yolo/images/test/p38_v9_00029.png: 640x640 1 lesion, 74.0ms
image 150/273 /content/cadica_yolo/images/test/p38_v9_00030.png: 640x640 1 lesion, 75.1ms
image 151/273 /content/cadica_yolo/images/test/p38_v9_00031.png: 640x640 1 lesion, 75.5ms
image 152/273 /content/cadica_yolo/images/test/p38_v9_00032.png: 640x640 2 lesions, 76.0ms
image 153/273 /content/cadica_yolo/images/test/p38_v9_00033.png: 640x640 2 lesions, 79.1ms
image 154/273 /content/cadica_yolo/images/test/p5_v1_00022.png: 640x640 1 lesion, 87.4ms
image 155/273 /content/cadica_yolo/images/test/p5_v1_00023.png: 640x640 1 lesion, 86.4ms
image 156/273 /content/cadica_yolo/images/test/p5_v1_00024.png: 640x640 2 lesions, 80.4ms
image 157/273 /content/cadica_yolo/images/test/p5_v1_00025.png: 640x640 1 lesion, 81.2ms
image 158/273 /content/cadica_yolo/images/test/p5_v1_00026.png: 640x640 1 lesion, 82.4ms
image 159/273 /content/cadica_yolo/images/test/p5_v1_00027.png: 640x640 2 lesions, 54.0ms
image 160/273 /content/cadica_yolo/images/test/p5_v1_00028.png: 640x640 1 lesion, 55.3ms
image 161/273 /content/cadica_yolo/images/test/p5_v1_00029.png: 640x640 1 lesion, 59.9ms
image 162/273 /content/cadica_yolo/images/test/p5_v1_00030.png: 640x640 1 lesion, 53.7ms
image 163/273 /content/cadica_yolo/images/test/p5_v1_00031.png: 640x640 1 lesion, 51.4ms
image 164/273 /content/cadica_yolo/images/test/p5_v1_00032.png: 640x640 (no detections), 51.4ms
image 165/273 /content/cadica_yolo/images/test/p5_v2_00017.png: 640x640 5 lesions, 51.0ms
image 166/273 /content/cadica_yolo/images/test/p5_v2_00018.png: 640x640 1 lesion, 50.8ms
image 167/273 /content/cadica_yolo/images/test/p5_v2_00019.png: 640x640 1 lesion, 54.6ms
image 168/273 /content/cadica_yolo/images/test/p5_v2_00020.png: 640x640 1 lesion, 52.8ms
image 169/273 /content/cadica_yolo/images/test/p5_v2_00021.png: 640x640 (no detections), 50.1ms
image 170/273 /content/cadica_yolo/images/test/p5_v2_00022.png: 640x640 (no detections), 51.0ms
image 171/273 /content/cadica_yolo/images/test/p5_v2_00023.png: 640x640 1 lesion, 48.6ms
image 172/273 /content/cadica_yolo/images/test/p5_v2_00024.png: 640x640 (no detections), 51.1ms
image 173/273 /content/cadica_yolo/images/test/p5_v2_00025.png: 640x640 (no detections), 49.8ms
image 174/273 /content/cadica_yolo/images/test/p5_v2_00026.png: 640x640 2 lesions, 47.2ms
image 175/273 /content/cadica_yolo/images/test/p5_v2_00027.png: 640x640 (no detections), 49.8ms
image 176/273 /content/cadica_yolo/images/test/p5_v2_00028.png: 640x640 2 lesions, 51.5ms
image 177/273 /content/cadica_yolo/images/test/p5_v2_00029.png: 640x640 2 lesions, 47.7ms
image 178/273 /content/cadica_yolo/images/test/p5_v2_00030.png: 640x640 2 lesions, 49.2ms
image 179/273 /content/cadica_yolo/images/test/p5_v2_00032.png: 640x640 2 lesions, 49.2ms
image 180/273 /content/cadica_yolo/images/test/p5_v2_00033.png: 640x640 1 lesion, 56.0ms
image 181/273 /content/cadica_yolo/images/test/p5_v2_00034.png: 640x640 1 lesion, 49.1ms
image 182/273 /content/cadica_yolo/images/test/p5_v3_00012.png: 640x640 1 lesion, 48.6ms
image 183/273 /content/cadica_yolo/images/test/p5_v3_00013.png: 640x640 2 lesions, 47.5ms
image 184/273 /content/cadica_yolo/images/test/p5_v3_00014.png: 640x640 1 lesion, 53.9ms
image 185/273 /content/cadica_yolo/images/test/p5_v3_00015.png: 640x640 1 lesion, 48.5ms
image 186/273 /content/cadica_yolo/images/test/p5_v3_00016.png: 640x640 (no detections), 49.3ms
image 187/273 /content/cadica_yolo/images/test/p5_v3_00017.png: 640x640 1 lesion, 47.0ms
image 188/273 /content/cadica_yolo/images/test/p5_v3_00018.png: 640x640 2 lesions, 47.6ms
image 189/273 /content/cadica_yolo/images/test/p5_v3_00019.png: 640x640 (no detections), 48.0ms
image 190/273 /content/cadica_yolo/images/test/p5_v3_00020.png: 640x640 (no detections), 47.6ms
image 191/273 /content/cadica_yolo/images/test/p5_v3_00021.png: 640x640 1 lesion, 47.8ms
image 192/273 /content/cadica_yolo/images/test/p5_v3_00022.png: 640x640 (no detections), 48.4ms
image 193/273 /content/cadica_yolo/images/test/p5_v3_00023.png: 640x640 2 lesions, 47.9ms
image 194/273 /content/cadica_yolo/images/test/p5_v3_00024.png: 640x640 (no detections), 60.9ms
image 195/273 /content/cadica_yolo/images/test/p5_v3_00025.png: 640x640 (no detections), 53.1ms
image 196/273 /content/cadica_yolo/images/test/p5_v3_00026.png: 640x640 1 lesion, 48.2ms
image 197/273 /content/cadica_yolo/images/test/p5_v3_00027.png: 640x640 (no detections), 48.3ms
image 198/273 /content/cadica_yolo/images/test/p5_v3_00028.png: 640x640 1 lesion, 47.6ms
image 199/273 /content/cadica_yolo/images/test/p5_v3_00029.png: 640x640 2 lesions, 47.7ms
image 200/273 /content/cadica_yolo/images/test/p5_v3_00030.png: 640x640 1 lesion, 47.3ms
image 201/273 /content/cadica_yolo/images/test/p5_v3_00031.png: 640x640 1 lesion, 46.6ms
image 202/273 /content/cadica_yolo/images/test/p5_v3_00032.png: 640x640 1 lesion, 47.1ms
image 203/273 /content/cadica_yolo/images/test/p5_v3_00033.png: 640x640 (no detections), 46.7ms
image 204/273 /content/cadica_yolo/images/test/p5_v3_00034.png: 640x640 (no detections), 46.9ms
image 205/273 /content/cadica_yolo/images/test/p5_v6_00017.png: 640x640 4 lesions, 46.8ms
image 206/273 /content/cadica_yolo/images/test/p5_v6_00018.png: 640x640 1 lesion, 47.1ms
image 207/273 /content/cadica_yolo/images/test/p5_v6_00019.png: 640x640 1 lesion, 46.7ms
image 208/273 /content/cadica_yolo/images/test/p5_v6_00020.png: 640x640 (no detections), 48.9ms
image 209/273 /content/cadica_yolo/images/test/p5_v6_00021.png: 640x640 1 lesion, 48.8ms
image 210/273 /content/cadica_yolo/images/test/p5_v6_00022.png: 640x640 1 lesion, 47.1ms
image 211/273 /content/cadica_yolo/images/test/p5_v6_00023.png: 640x640 1 lesion, 50.2ms
image 212/273 /content/cadica_yolo/images/test/p5_v6_00024.png: 640x640 1 lesion, 49.1ms
image 213/273 /content/cadica_yolo/images/test/p5_v7_00009.png: 640x640 4 lesions, 48.5ms
image 214/273 /content/cadica_yolo/images/test/p5_v7_00010.png: 640x640 (no detections), 48.7ms
image 215/273 /content/cadica_yolo/images/test/p5_v7_00011.png: 640x640 1 lesion, 55.0ms
image 216/273 /content/cadica_yolo/images/test/p5_v7_00012.png: 640x640 2 lesions, 48.7ms
image 217/273 /content/cadica_yolo/images/test/p5_v7_00013.png: 640x640 (no detections), 55.3ms
image 218/273 /content/cadica_yolo/images/test/p5_v7_00014.png: 640x640 1 lesion, 48.5ms
image 219/273 /content/cadica_yolo/images/test/p5_v7_00015.png: 640x640 3 lesions, 56.0ms

[ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'lesion'}
 obb: None
 orig_img: array([[[32, 32, 32],
         [30, 30, 30],
         [30, 30, 30],
         ...,
         [13, 13, 13],
         [15, 15, 15],
         [18, 18, 18]],

        [[30, 30, 30],
         [32, 32, 32],
         [34, 34, 34],
         ...,
         [17, 17, 17],
         [17, 17, 17],
         [18, 18, 18]],

        [[34, 34, 34],
         [34, 34, 34],
         [34, 34, 34],
         ...,
         [22, 22, 22],
         [20, 20, 20],
         [20, 20, 20]],

        ...,

        [[15, 15, 15],
         [15, 15, 15],
         [15, 15, 15],
         ...,
         [ 6,  6,  6],
         [ 6,  6,  6],
         [ 5,  5,  5]],

        [[11, 11, 11],
         [13, 13, 13],
         [13, 13, 13],
         ...,
         [ 6,  6,  6],
         [ 3,  3,  3],
         [ 1,  1,  1]],

        [[13, 13, 13],
         [13, 13, 13],
         [13, 13, 13],
         ...,
         [ 6,  6,  6],
         [ 5,  5,  5],
         [ 0,  0,  0]]], dtype=uint8)
 orig_shape: (512, 512)
 path: '/content/cadica_yolo/images/test/p28_v6_00013.png'
 probs: None
 save_dir: '/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/predict_test_v3'
 semantic_mask: None
 speed: {'preprocess': 3.4700610000300003, 'inference': 72.3271740000655, 'postprocess': 0.945230999946034},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'lesion'}
 obb: None
 orig_img: array([[[32, 32, 32],
         [34, 34, 34],
         [32, 32, 32],
         ...,
         [17, 17, 17],
         [13, 13, 13],
         [13, 13, 13]],

        [[32, 32, 32],
         [34, 34, 34],
         [32, 32, 32],
         ...,
         [18, 18, 18],
         [17, 17, 17],
         [17, 17, 17]],

        [[34, 34, 34],
         [34, 34, 34],
         [30, 30, 30],
         ...,
         [20, 20, 20],
         [20, 20, 20],
         [18, 18, 18]],

        ...,

        [[13, 13, 13],
         [13, 13, 13],
         [15, 15, 15],
         ...,
         [10, 10, 10],
         [ 5,  5,  5],
         [ 1,  1,  1]],

        [[13, 13, 13],
         [13, 13, 13],
         [13, 13, 13],
         ...,
         [ 6,  6,  6],
         [ 3,  3,  3],
         [ 1,  1,  1]],

        [[11, 11, 11],
         [11, 11, 11],
         [11, 11, 11],
         ...,
         [ 5,  5,  5],
         [ 3,  3,  3],
         [ 1,  1,  1]]], dtype=uint8)
 orig_shape: (512, 512)
 path: '/content/cadica_yolo/images/test/p28_v6_00014.png'
 probs: None
 save_dir: '/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/predict_test_v3'
 semantic_mask: None
 speed: {'preprocess': 3.0653349999738566, 'inference': 69.69030900006601, 'postprocess': 0.6314319999773943},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'lesion'}
 obb: None
 orig_img: array([[[37, 37, 37],
         [34, 34, 34],
         [32, 32, 32],
         ...,
         [27, 27, 27],
         [22, 22, 22],
         [18, 18, 18]],

        [[34, 34, 34],
         [34, 34, 34],
         [34, 34, 34],
         ...,
         [27, 27, 27],
         [22, 22, 22],
         [20, 20, 20]],

        [[32, 32, 32],
         [32, 32, 32],
         [29, 29, 29],
         ...,
         [29, 29, 29],
         [27, 27, 27],
         [22, 22, 22]],

        ...,

        [[15, 15, 15],
         [15, 15, 15],
         [17, 17, 17],
         ...,
         [ 8,  8,  8],
         [ 8,  8,  8],
         [ 5,  5,  5]],

        [[15, 15, 15],
         [15, 15, 15],
         [15, 15, 15],
         ...,
         [ 6,  6,  6],
         [ 6,  6,  6],
         [ 3,  3,  3]],

        [[15, 15, 15],
         [13, 13, 13],
         [13, 13, 13],
         ...,
         [ 6,  6,  6],
         [ 5,  5,  5],
         [ 1,  1,  1]]], dtype=uint8)
 orig_shape: (512, 512)
 path: '/content/cadica_yolo/images/test/p28_v6_00015.png'
 probs: None
 save_dir: '/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/predict_test_v3'
 semantic_mask: None
 speed: {'preprocess': 2.6588929999888933, 'inference': 70.34944699989865, 'postprocess': 0.708488999975998},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'lesion'}
 obb: None
 orig_img: array([[[35, 35, 35],
         [34, 34, 34],
         [37, 37, 37],
         ...,
         [20, 20, 20],
         [20, 20, 20],
         [22, 22, 22]],

        [[34, 34, 34],
         [30, 30, 30],
         [34, 34, 34],
         ...,
         [25, 25, 25],
         [25, 25, 25],
         [22, 22, 22]],

        [[34, 34, 34],
         [32, 32, 32],
         [32, 32, 32],
         ...,
         [27, 27, 27],
         [27, 27, 27],
         [25, 25, 25]],

        ...,

        [[17, 17, 17],
         [17, 17, 17],
         [17, 17, 17],
         ...,
         [10, 10, 10],
         [ 6,  6,  6],
         [ 5,  5,  5]],

        [[17, 17, 17],
         [17, 17, 17],
         [17, 17, 17],
         ...,
         [ 6,  6,  6],
         [ 3,  3,  3],
         [ 5,  5,  5]],

        [[15, 15, 15],
         [15, 15, 15],
         [17, 17, 17],
         ...,
         [ 3,  3,  3],
         [ 3,  3,  3],
         [ 3,  3,  3]]], dtype=uint8)
 orig_shape: (512, 512)
 path: '/content/cadica_yolo/images/test/p28_v6_00020.png'
 probs: None
 save_dir: '/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/predict_test_v3'
 semantic_mask: None
 speed: {'preprocess': 2.4610839999468226, 'inference': 69.44323400000485, 'postprocess': 0.689502000000175},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'lesion'}
 obb: None
 orig_img: array([[[30, 30, 30],
         [32, 32, 32],
         [35, 35, 35],
         ...,
         [23, 23, 23],
         [27, 27, 27],
         [25, 25, 25]],

        [[34, 34, 34],
         [30, 30, 30],
         [32, 32, 32],
         ...,
         [29, 29, 29],
         [29, 29, 29],
         [25, 25, 25]],

        [[35, 35, 35],
         [32, 32, 32],
         [34, 34, 34],
         ...,
         [32, 32, 32],
         [30, 30, 30],
         [29, 29, 29]],

        ...,

        [[17, 17, 17],
         [17, 17, 17],
         [15, 15, 15],
         ...,
         [ 8,  8,  8],
         [ 6,  6,  6],
         [ 5,  5,  5]],

        [[15, 15, 15],
         [15, 15, 15],
         [13, 13, 13],
         ...,
         [ 6,  6,  6],
         [ 8,  8,  8],
         [ 6,  6,  6]],

        [[15, 15, 15],
         [11, 11, 11],
         [11, 11, 11],
         ...,
         [ 5,  5,  5],
         [ 6,  6,  6],
         [ 5,  5,  5]]], dtype=uint8)
 orig_shape: (512, 512)
 path: '/content/cadica_yolo/images/test/p28_v6_00021.png'
 probs: None
 save_dir: '/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/predict_test_v3'
 semantic_mask: None
 speed: {'preprocess': 2.8610619999653863, 'inference': 55.9234300000071, 'postprocess': 0.6852870000102484},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'lesion'}
 obb: None
 orig_img: array([[[30, 30, 30],
         [30, 30, 30],
         [34, 34, 34],
         ...,
         [29, 29, 29],
         [23, 23, 23],
         [18, 18, 18]],

        [[34, 34, 34],
         [32, 32, 32],
         [34, 34, 34],
         ...,
         [29, 29, 29],
         [25, 25, 25],
         [27, 27, 27]],

        [[35, 35, 35],
         [35, 35, 35],
         [35, 35, 35],
         ...,
         [30, 30, 30],
         [32, 32, 32],
         [34, 34, 34]],

        ...,

        [[11, 11, 11],
         [13, 13, 13],
         [15, 15, 15],
         ...,
         [11, 11, 11],
         [10, 10, 10],
         [ 6,  6,  6]],

        [[13, 13, 13],
         [17, 17, 17],
         [15, 15, 15],
         ...,
         [ 6,  6,  6],
         [ 5,  5,  5],
         [ 3,  3,  3]],

        [[15, 15, 15],
         [15, 15, 15],
         [13, 13, 13],
         ...,
         [ 5,  5,  5],
         [ 5,  5,  5],
         [ 5,  5,  5]]], dtype=uint8)
 orig_shape: (512, 512)
 path: '/content/cadica_yolo/images/test/p28_v6_00022.png'
 probs: None
 save_dir: '/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/predict_test_v3'
 semantic_mask: None
 speed: {'preprocess': 2.410704999988411, 'inference': 55.3645109999934, 'postprocess': 0.6184040000789537},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'lesion'}
 obb: None
 orig_img: array([[[27, 27, 27],
         [32, 32, 32],
         [34, 34, 34],
         ...,
         [23, 23, 23],
         [23, 23, 23],
         [22, 22, 22]],

        [[32, 32, 32],
         [35, 35, 35],
         [35, 35, 35],
         ...,
         [27, 27, 27],
         [25, 25, 25],
         [23, 23, 23]],

        [[32, 32, 32],
         [34, 34, 34],
         [32, 32, 32],
         ...,
         [27, 27, 27],
         [29, 29, 29],
         [27, 27, 27]],

        ...,

        [[18, 18, 18],
         [20, 20, 20],
         [20, 20, 20],
         ...,
         [ 6,  6,  6],
         [ 5,  5,  5],
         [ 8,  8,  8]],

        [[18, 18, 18],
         [18, 18, 18],
         [18, 18, 18],
         ...,
         [ 8,  8,  8],
         [ 6,  6,  6],
         [ 8,  8,  8]],

        [[20, 20, 20],
         [17, 17, 17],
         [18, 18, 18],
         ...,
         [ 6,  6,  6],
         [ 6,  6,  6],
         [ 5,  5,  5]]], dtype=uint8)
 orig_shape: (512, 512)
 path: '/content/cadica_yolo/images/test/p28_v6_00025.png'
 probs: None
 save_dir: '/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/predict_test_v3'
 semantic_mask: None
 speed: {'preprocess': 2.308785999957763, 'inference': 54.16389999993498, 'postprocess': 0.592785000094409},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'lesion'}
 obb: None
 orig_img: array([[[34, 34, 34],
         [37, 37, 37],
         [34, 34, 34],
         ...,
         [27, 27, 27],
         [29, 29, 29],
         [29, 29, 29]],

        [[30, 30, 30],
         [34, 34, 34],
         [35, 35, 35],
         ...,
         [29, 29, 29],
         [30, 30, 30],
         [30, 30, 30]],

        [[30, 30, 30],
         [32, 32, 32],
         [34, 34, 34],
         ...,
         [34, 34, 34],
         [35, 35, 35],
         [35, 35, 35]],

        ...,

        [[18, 18, 18],
         [15, 15, 15],
         [17, 17, 17],
         ...,
         [ 6,  6,  6],
         [ 8,  8,  8],
         [ 5,  5,  5]],

        [[11, 11, 11],
         [11, 11, 11],
         [13, 13, 13],
         ...,
         [ 6,  6,  6],
         [ 6,  6,  6],
         [ 5,  5,  5]],

        [[11, 11, 11],
         [13, 13, 13],
         [15, 15, 15],
         ...,
         [ 8,  8,  8],
         [ 5,  5,  5],
         [ 6,  6,  6]]], dtype=uint8)
 orig_shape: (512, 512)
 path: '/content/cadica_yolo/images/test/p28_v6_00028.png'
 probs: None
 save_dir: '/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/predict_test_v3'
 semantic_mask: None
 speed: {'preprocess': 3.0456219999450695, 'inference': 55.96871700004158, 'postprocess': 0.6009249999578969},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'lesion'}
 obb: None
 orig_img: array([[[34, 34, 34],
         [34, 34, 34],
         [34, 34, 34],
         ...,
         [23, 23, 23],
         [25, 25, 25],
         [22, 22, 22]],

        [[34, 34, 34],
         [32, 32, 32],
         [30, 30, 30],
         ...,
         [29, 29, 29],
         [27, 27, 27],
         [29, 29, 29]],

        [[32, 32, 32],
         [35, 35, 35],
         [34, 34, 34],
         ...,
         [34, 34, 34],
         [32, 32, 32],
         [35, 35, 35]],

        ...,

        [[13, 13, 13],
         [15, 15, 15],
         [13, 13, 13],
         ...,
         [ 6,  6,  6],
         [ 6,  6,  6],
         [ 3,  3,  3]],

        [[13, 13, 13],
         [13, 13, 13],
         [13, 13, 13],
         ...,
         [ 6,  6,  6],
         [ 6,  6,  6],
         [ 5,  5,  5]],

        [[10, 10, 10],
         [13, 13, 13],
         [13, 13, 13],
         ...,
         [ 8,  8,  8],
         [ 6,  6,  6],
         [ 1,  1,  1]]], dtype=uint8)
 orig_shape: (512, 512)
 path: '/content/cadica_yolo/images/test/p28_v6_00029.png'
 probs: None
 save_dir: '/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/predict_test_v3'
 semantic_mask: None
 speed: {'preprocess': 2.5036880000470774, 'inference': 55.471667000006164, 'postprocess': 0.6499159999293624},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'lesion'}
 obb: None
 orig_img: array([[[29, 29, 29],
         [32, 32, 32],
         [32, 32, 32],
         ...,
         [29, 29, 29],
         [27, 27, 27],
         [27, 27, 27]],

        [[32, 32, 32],
         [32, 32, 32],
         [32, 32, 32],
         ...,
         [30, 30, 30],
         [30, 30, 30],
         [29, 29, 29]],

        [[32, 32, 32],
         [32, 32, 32],
         [32, 32, 32],
         ...,
         [34, 34, 34],
         [34, 34, 34],
         [32, 32, 32]],

        ...,

        [[17, 17, 17],
         [18, 18, 18],
         [17, 17, 17],
         ...,
         [10, 10, 10],
         [ 8,  8,  8],
         [ 5,  5,  5]],

        [[15, 15, 15],
         [17, 17, 17],
         [15, 15, 15],
         ...,
         [ 8,  8,  8],
         [ 6,  6,  6],
         [ 5,  5,  5]],

        [[15, 15, 15],
         [15, 15, 15],
         [15, 15, 15],
         ...,
         [ 8,  8,  8],
         [ 3,  3,  3],
         [ 3,  3,  3]]], dtype=uint8)
 orig_shape: (512, 512)
 path: '/content/cadica_yolo/images/test/p28_v6_00030.png'
 probs: None
 save_dir: '/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/predict_test_v3'
 semantic_mask: None
 speed: {'preprocess': 2.311974999997801, 'inference': 51.38562799993451, 'postprocess': 0.5700940000679111},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'lesion'}
 obb: None
 orig_img: array([[[42, 42, 42],
         [46, 46, 46],
         [47, 47, 47],
         ...,
         [29, 29, 29],
         [27, 27, 27],
         [29, 29, 29]],

        [[42, 42, 42],
         [44, 44, 44],
         [46, 46, 46],
         ...,
         [34, 34, 34],
         [32, 32, 32],
         [34, 34, 34]],

        [[46, 46, 46],
         [47, 47, 47],
         [44, 44, 44],
         ...,
         [39, 39, 39],
         [34, 34, 34],
         [34, 34, 34]],

        ...,

        [[30, 30, 30],
         [32, 32, 32],
         [34, 34, 34],
         ...,
         [34, 34, 34],
         [30, 30, 30],
         [25, 25, 25]],

        [[32, 32, 32],
         [32, 32, 32],
         [30, 30, 30],
         ...,
         [30, 30, 30],
         [27, 27, 27],
         [23, 23, 23]],

        [[34, 34, 34],
         [30, 30, 30],
         [29, 29, 29],
         ...,
         [32, 32, 32],
         [23, 23, 23],
         [18, 18, 18]]], dtype=uint8)
 orig_shape: (512, 512)
 path: '/content/cadica_yolo/images/test/p28_v7_00023.png'
 probs: None
 save_dir: '/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/predict_test_v3'
 semantic_mask: None
 speed: {'preprocess': 3.039039999976012, 'inference': 52.34895099999903, 'postprocess': 0.5558950000477125},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'lesion'}
 obb: None
 orig_img: array([[[47, 47, 47],
         [49, 49, 49],
         [51, 51, 51],
         ...,
         [32, 32, 32],
         [30, 30, 30],
         [29, 29, 29]],

        [[49, 49, 49],
         [51, 51, 51],
         [53, 53, 53],
         ...,
         [35, 35, 35],
         [34, 34, 34],
         [32, 32, 32]],

        [[51, 51, 51],
         [49, 49, 49],
         [53, 53, 53],
         ...,
         [37, 37, 37],
         [37, 37, 37],
         [34, 34, 34]],

        ...,

        [[35, 35, 35],
         [34, 34, 34],
         [34, 34, 34],
         ...,
         [32, 32, 32],
         [30, 30, 30],
         [27, 27, 27]],

        [[37, 37, 37],
         [34, 34, 34],
         [32, 32, 32],
         ...,
         [30, 30, 30],
         [27, 27, 27],
         [29, 29, 29]],

        [[32, 32, 32],
         [30, 30, 30],
         [32, 32, 32],
         ...,
         [29, 29, 29],
         [29, 29, 29],
         [29, 29, 29]]], dtype=uint8)
 orig_shape: (512, 512)
 path: '/content/cadica_yolo/images/test/p28_v7_00024.png'
 probs: None
 save_dir: '/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/predict_test_v3'
 semantic_mask: None
 speed: {'preprocess': 2.8142780000735, 'inference': 49.99790799990933, 'postprocess': 0.5478890000176762},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'lesion'}
 obb: None
 orig_img: array([[[49, 49, 49],
         [49, 49, 49],
         [54, 54, 54],
         ...,
         [37, 37, 37],
         [32, 32, 32],
         [30, 30, 30]],

        [[53, 53, 53],
         [54, 54, 54],
         [54, 54, 54],
         ...,
         [41, 41, 41],
         [37, 37, 37],
         [35, 35, 35]],

        [[53, 53, 53],
         [54, 54, 54],
         [56, 56, 56],
         ...,
         [44, 44, 44],
         [41, 41, 41],
         [39, 39, 39]],

        ...,

        [[32, 32, 32],
         [34, 34, 34],
         [37, 37, 37],
         ...,
         [37, 37, 37],
         [32, 32, 32],
         [32, 32, 32]],

        [[32, 32, 32],
         [30, 30, 30],
         [34, 34, 34],
         ...,
         [32, 32, 32],
         [29, 29, 29],
         [27, 27, 27]],

        [[30, 30, 30],
         [29, 29, 29],
         [30, 30, 30],
         ...,
         [30, 30, 30],
         [23, 23, 23],
         [25, 25, 25]]], dtype=uint8)
 orig_shape: (512, 512)
 path: '/content/cadica_yolo/images/test/p28_v7_00025.png'
 probs: None
 save_dir: '/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/predict_test_v3'
 semantic_mask: None
 speed: {'preprocess': 3.9876419999700374, 'inference': 52.33581499999218, 'postprocess': 0.5983930000184046},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'lesion'}
 obb: None
 orig_img: array([[[51, 51, 51],
         [49, 49, 49],
         [49, 49, 49],
         ...,
         [35, 35, 35],
         [35, 35, 35],
         [37, 37, 37]],

        [[47, 47, 47],
         [51, 51, 51],
         [51, 51, 51],
         ...,
         [37, 37, 37],
         [39, 39, 39],
         [41, 41, 41]],

        [[51, 51, 51],
         [53, 53, 53],
         [51, 51, 51],
         ...,
         [42, 42, 42],
         [41, 41, 41],
         [44, 44, 44]],

        ...,

        [[34, 34, 34],
         [30, 30, 30],
         [30, 30, 30],
         ...,
         [35, 35, 35],
         [32, 32, 32],
         [29, 29, 29]],

        [[29, 29, 29],
         [30, 30, 30],
         [30, 30, 30],
         ...,
         [32, 32, 32],
         [29, 29, 29],
         [27, 27, 27]],

        [[29, 29, 29],
         [27, 27, 27],
         [29, 29, 29],
         ...,
         [32, 32, 32],

In [ ]:
# @title size올림
model = RTDETR("rtdetr-l.pt")  # 새로 시작 (baseline과 공정 비교 위해 처음부터)
model.train(
    data="/content/cadica_yolo/data.yaml",
    epochs=50,
    imgsz=768,
    batch=4,           # 768로 올리면 T4 메모리 부족 가능 → OOM나면 2로
    lr0=0.0005,
    optimizer="AdamW",
    patience=20,
    amp=True,
    cache=True,
    project="/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result",
    name="train_imgsz768",
)

Ultralytics 8.4.95 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=True, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/cadica_yolo/data.yaml, degrees=0.0, deterministic=True, device=, dfl=1.5, dis=6.0, distill_model=None, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=768, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.0005, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=rtdetr-l.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=train_imgsz768, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_imgsz768, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1
WARNING ⚠️ no model scale passed. Assuming scale='l'.

                   from  n    params  module                                       arguments
  0                  -1  1     25248  ultralytics.nn.modules.block.HGStem          [3, 32, 48]
  1                  -1  6    155072  ultralytics.nn.modules.block.HGBlock         [48, 48, 128, 3, 6]
  2                  -1  1      1408  ultralytics.nn.modules.conv.DWConv           [128, 128, 3, 2, 1, False]
  3                  -1  6    839296  ultralytics.nn.modules.block.HGBlock         [128, 96, 512, 3, 6]
  4                  -1  1      5632  ultralytics.nn.modules.conv.DWConv           [512, 512, 3, 2, 1, False]
  5                  -1  6   1695360  ultralytics.nn.modules.block.HGBlock         [512, 192, 1024, 5, 6, True, False]
  6                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  7                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  8                  -1  1     11264  ultralytics.nn.modules.conv.DWConv           [1024, 1024, 3, 2, 1, False]
  9                  -1  6   6708480  ultralytics.nn.modules.block.HGBlock         [1024, 384, 2048, 5, 6, True, False]
 10                  -1  1    524800  ultralytics.nn.modules.conv.Conv             [2048, 256, 1, 1, None, 1, 1, False]
 11                  -1  1    789760  ultralytics.nn.modules.transformer.AIFI      [256, 1024, 8]
 12                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14                   7  1    262656  ultralytics.nn.modules.conv.Conv             [1024, 256, 1, 1, None, 1, 1, False]
 15            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 17                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 18                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 19                   3  1    131584  ultralytics.nn.modules.conv.Conv             [512, 256, 1, 1, None, 1, 1, False]
 20            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 22                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 23            [-1, 17]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 24                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 25                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 26            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 27                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 28        [21, 24, 27]  1   7303907  ultralytics.nn.modules.head.RTDETRDecoder    [1, [256, 256, 256]]
rt-detr-l summary: 465 layers, 32,808,131 parameters, 32,808,131 gradients, 108.0 GFLOPs

Transferred 926/941 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 98.3MB/s 0.1s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 450.8±657.4 MB/s, size: 99.5 KB)
train: Scanning /content/cadica_yolo/labels/train... 3077 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 3077/3077 837.1it/s 3.7s
train: New cache created: /content/cadica_yolo/labels/train.cache
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.
train: Caching images (5.1GB RAM): 100% ━━━━━━━━━━━━ 3077/3077 148.4it/s 20.7s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.4±0.9 ms, read: 1315.6±854.9 MB/s, size: 95.7 KB)
val: Scanning /content/cadica_yolo/labels/val.cache... 335 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 335/335 13.4Mit/s 0.0s
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.
val: Caching images (0.6GB RAM): 100% ━━━━━━━━━━━━ 335/335 118.6it/s 2.8s
optimizer: AdamW(lr=0.0005, momentum=0.937) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.0005), 226 bias(decay=0.0)
Plotting labels to /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_imgsz768/labels.jpg...
Image sizes 768 train, 768 val
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_imgsz768
Starting training for 50 epochs...

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       1/50      4.24G      2.007      13.32      0.936          5        768: 0% ──────────── 0/770  6.1s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       1/50      4.47G      1.404     0.6143     0.4608          1        768: 100% ━━━━━━━━━━━━ 770/770 1.9it/s 6:39
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 3.1it/s 13.7s
                   all        335        506    0.00663      0.221     0.0202    0.00301

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       2/50      4.47G      1.043     0.6998     0.1542         18        768: 0% ──────────── 0/770  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       2/50      4.47G     0.9064     0.9434     0.2236          0        768: 100% ━━━━━━━━━━━━ 770/770 2.0it/s 6:22
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.4it/s 9.6s
                   all        335        506     0.0329      0.117     0.0164    0.00369

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       3/50      4.47G     0.8072     0.8664     0.1446         11        768: 0% ──────────── 0/770  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       3/50      4.48G     0.6754      1.077     0.1586          2        768: 100% ━━━━━━━━━━━━ 770/770 2.0it/s 6:26
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.3it/s 9.8s
                   all        335        506     0.0569      0.176     0.0303     0.0086

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       4/50      4.48G     0.7839     0.9711     0.1867          9        768: 0% ──────────── 0/770  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       4/50      4.48G     0.5985      1.077      0.148          2        768: 100% ━━━━━━━━━━━━ 770/770 2.0it/s 6:24
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.3it/s 9.7s
                   all        335        506     0.0635      0.158     0.0328     0.0111

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       5/50      4.48G     0.8123     0.8468     0.2266          7        768: 0% ──────────── 0/770  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       5/50      4.48G     0.6013     0.9842     0.1482          1        768: 100% ━━━━━━━━━━━━ 770/770 2.0it/s 6:22
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.4it/s 9.6s
                   all        335        506      0.167      0.281        0.1      0.034

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       6/50      4.48G     0.5879     0.8764     0.1402          6        768: 0% ──────────── 0/770  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       6/50      4.48G     0.6597     0.8033     0.1704          0        768: 100% ━━━━━━━━━━━━ 770/770 2.0it/s 6:21
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.3it/s 9.8s
                   all        335        506      0.201      0.208      0.107     0.0288

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       7/50      4.48G      0.687      1.375     0.1646          3        768: 0% ──────────── 0/770  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       7/50      4.48G     0.6626     0.8193      0.173          0        768: 100% ━━━━━━━━━━━━ 770/770 2.0it/s 6:16
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.4it/s 9.6s
                   all        335        506       0.19        0.2     0.0707     0.0148

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       8/50      4.48G     0.6173      0.655     0.1309         11        768: 0% ──────────── 0/770  0.8s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       8/50      4.48G     0.6745     0.7057     0.1737          1        768: 100% ━━━━━━━━━━━━ 770/770 2.0it/s 6:19
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.4it/s 9.5s
                   all        335        506      0.213      0.281     0.0932     0.0201

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       9/50      4.48G     0.8542     0.6098     0.2717         13        768: 0% ──────────── 0/770  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       9/50      4.48G     0.6316     0.6915     0.1597          3        768: 100% ━━━━━━━━━━━━ 770/770 2.0it/s 6:18
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.3it/s 9.8s
                   all        335        506      0.121     0.0771     0.0309    0.00759

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      10/50      4.48G     0.5875     0.6228     0.1027         12        768: 0% ──────────── 0/770  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      10/50      4.48G     0.6137     0.6788     0.1547          0        768: 100% ━━━━━━━━━━━━ 770/770 2.0it/s 6:19
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.4it/s 9.6s
                   all        335        506      0.208      0.083     0.0586     0.0174

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      11/50      4.48G      0.637     0.5498     0.1523          7        768: 0% ──────────── 0/770  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      11/50      4.48G     0.5915     0.7062     0.1469          3        768: 100% ━━━━━━━━━━━━ 770/770 2.0it/s 6:18
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.3it/s 9.8s
                   all        335        506     0.0987      0.269     0.0413     0.0113

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      12/50      4.48G      1.017     0.5998     0.3373          8        768: 0% ──────────── 0/770  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      12/50      4.48G     0.6043      0.639     0.1525          1        768: 100% ━━━━━━━━━━━━ 770/770 2.0it/s 6:19
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.4it/s 9.6s
                   all        335        506      0.183     0.0929     0.0763     0.0222

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      13/50      4.48G     0.3024     0.4634    0.06545          6        768: 0% ──────────── 0/770  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      13/50      4.48G     0.5693     0.6393     0.1407          5        768: 100% ━━━━━━━━━━━━ 770/770 2.0it/s 6:19
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.3it/s 9.8s
                   all        335        506      0.208      0.142     0.0778     0.0227

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      14/50      4.48G     0.6764     0.5429     0.1085         15        768: 0% ──────────── 0/770  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      14/50      4.48G     0.5615     0.5942     0.1395          2        768: 100% ━━━━━━━━━━━━ 770/770 2.0it/s 6:19
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.4it/s 9.6s
                   all        335        506      0.178      0.176     0.0938     0.0265

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      15/50      4.48G     0.5232     0.5834    0.09598         10        768: 0% ──────────── 0/770  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      15/50      4.48G     0.5508     0.5732     0.1357          1        768: 100% ━━━━━━━━━━━━ 770/770 2.0it/s 6:19
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.4it/s 9.6s
                   all        335        506      0.147      0.144     0.0687     0.0218

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      16/50      4.48G     0.6378     0.9493     0.1124          8        768: 0% ──────────── 0/770  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      16/50      4.48G     0.5414      0.561     0.1309          2        768: 100% ━━━━━━━━━━━━ 770/770 2.0it/s 6:19
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.4it/s 9.5s
                   all        335        506      0.135      0.245     0.0919     0.0267

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      17/50      4.48G     0.5662     0.4456    0.08328         13        768: 0% ──────────── 0/770  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      17/50      4.48G     0.5547     0.5263     0.1357          2        768: 100% ━━━━━━━━━━━━ 770/770 2.0it/s 6:18
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.4it/s 9.5s
                   all        335        506      0.205      0.211     0.0969     0.0291

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      18/50      4.48G     0.4642     0.7891     0.0957          4        768: 0% ──────────── 0/770  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      18/50      4.48G     0.5353     0.5251     0.1303          3        768: 100% ━━━━━━━━━━━━ 770/770 2.0it/s 6:16
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.3it/s 9.8s
                   all        335        506       0.15      0.215     0.0718     0.0208

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      19/50      4.48G     0.5201     0.5428     0.1276         13        768: 0% ──────────── 0/770  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      19/50      4.48G      0.527     0.5159     0.1281          4        768: 100% ━━━━━━━━━━━━ 770/770 2.0it/s 6:17
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.3it/s 9.8s
                   all        335        506      0.145      0.229     0.0673     0.0213

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      20/50      4.48G     0.5657     0.5712      0.126          9        768: 0% ──────────── 0/770  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      20/50      4.48G     0.5252     0.5061     0.1307          2        768: 100% ━━━━━━━━━━━━ 770/770 2.0it/s 6:17
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.3it/s 9.7s
                   all        335        506      0.165      0.245     0.0853     0.0304

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      21/50      4.48G     0.4495     0.5047    0.08509         12        768: 0% ──────────── 0/770  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      21/50      4.48G     0.5145     0.4996     0.1248          7        768: 100% ━━━━━━━━━━━━ 770/770 2.0it/s 6:16
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.3it/s 9.7s
                   all        335        506      0.136      0.178     0.0458     0.0124

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      22/50      4.48G     0.4435     0.4877    0.08481         16        768: 0% ──────────── 0/770  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      22/50      4.48G     0.5051     0.5022     0.1229          7        768: 100% ━━━━━━━━━━━━ 770/770 2.0it/s 6:18
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.3it/s 9.7s
                   all        335        506       0.18      0.208     0.0875     0.0256

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      23/50      4.48G      0.425     0.4201    0.07301         10        768: 0% ──────────── 0/770  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      23/50      4.48G     0.5044     0.4981     0.1219          4        768: 100% ━━━━━━━━━━━━ 770/770 2.1it/s 6:15
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.3it/s 9.8s
                   all        335        506      0.169      0.225     0.0873     0.0275

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      24/50      4.48G     0.4703     0.5865     0.3139          3        768: 0% ──────────── 0/770  0.9s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      24/50      4.48G     0.4957     0.4921     0.1195          2        768: 100% ━━━━━━━━━━━━ 770/770 2.0it/s 6:18
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.3it/s 9.8s
                   all        335        506      0.146      0.178     0.0589     0.0178

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      25/50      4.48G     0.4245     0.4158    0.09947          9        768: 0% ──────────── 0/770  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      25/50      4.48G     0.4843     0.4854      0.116          0        768: 100% ━━━━━━━━━━━━ 770/770 2.0it/s 6:17
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.3it/s 9.7s
                   all        335        506       0.13      0.217     0.0615     0.0199
EarlyStopping: Training stopped early as no improvement observed in last 20 epochs. Best results observed at epoch 5, best model saved as best.pt.
To update EarlyStopping(patience=20) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

25 epochs completed in 2.849 hours.
Optimizer stripped from /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_imgsz768/weights/last.pt, 66.3MB
Optimizer stripped from /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_imgsz768/weights/best.pt, 66.3MB

Validating /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_imgsz768/weights/best.pt...
Ultralytics 8.4.95 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
rt-detr-l summary: 310 layers, 31,985,795 parameters, 0 gradients, 103.4 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 42/42 4.9it/s 8.5s
                   all        335        506      0.166      0.279      0.101     0.0342
Speed: 0.6ms preprocess, 21.3ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_imgsz768

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x78f70585ff20>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[    0.42857,     0.42857,     0.42857,     0.42857,     0.42857,     0.42857,     0.35484,     0.35484,     0.35484,     0.35484,     0.35484,     0.35484,     0.35484,     0.35484,     0.35484,     0.35484,     0.35484,     0.35484,     0.35484,     0.35484,     0.35484,     0.35484,     0.30233,
            0.30233,     0.30233,     0.30233,     0.28814,     0.28814,     0.28814,     0.28814,     0.28814,     0.28814,     0.28814,     0.28814,     0.28767,     0.28767,     0.28767,     0.28767,     0.28767,     0.28767,     0.28767,     0.28767,     0.28571,     0.28571,     0.27692,     0.27692,
            0.27692,     0.27692,     0.27692,     0.27692,     0.27692,     0.27692,     0.27692,     0.27692,     0.27692,     0.27692,     0.27692,     0.27692,     0.27692,     0.27692,     0.27692,     0.27692,     0.27692,     0.27692,     0.27692,     0.27692,     0.27692,     0.27692,     0.27692,
            0.27692,     0.27692,     0.27692,     0.27612,     0.27612,     0.27338,     0.27338,     0.27027,     0.27027,     0.27027,     0.24551,     0.24551,     0.23864,     0.23864,     0.23784,     0.23784,     0.23784,     0.23784,     0.23684,     0.23684,     0.23318,     0.23318,     0.23318,
            0.23318,     0.23318,     0.23318,     0.23318,     0.23318,     0.23318,     0.23318,     0.23318,     0.23318,     0.23318,     0.23318,     0.23176,     0.23176,     0.23176,     0.23176,     0.23045,     0.23045,     0.23045,     0.23045,     0.22568,     0.22568,     0.22568,     0.22568,
            0.22152,     0.22152,     0.22152,     0.22152,     0.22152,     0.22152,     0.22152,     0.22152,     0.22152,     0.22152,     0.22152,     0.22152,     0.22152,     0.22152,     0.22152,     0.22152,     0.22152,     0.22152,     0.22152,     0.22152,     0.22152,     0.22152,     0.22152,
            0.22152,     0.21646,     0.21646,     0.21607,     0.21607,     0.21607,     0.21607,     0.21607,     0.21607,     0.21607,     0.21607,     0.21607,     0.21607,     0.21607,     0.21607,     0.21607,     0.21585,     0.21585,     0.21579,     0.21579,     0.21579,     0.21579,     0.21579,
            0.21579,     0.21337,     0.21337,     0.21296,     0.21296,     0.21296,     0.21296,     0.21296,     0.21296,     0.21296,     0.21296,     0.21296,     0.21296,     0.21296,     0.21296,     0.21296,     0.21296,     0.21296,     0.21296,     0.21296,     0.21296,     0.21076,     0.21076,
            0.21076,     0.21076,     0.20911,     0.20911,     0.20911,     0.20911,     0.20911,     0.20911,     0.20911,     0.20911,     0.20911,     0.20911,     0.20911,     0.20911,     0.20911,     0.20911,       0.204,       0.204,     0.20312,     0.20312,     0.20312,     0.20312,     0.20038,
            0.20038,     0.19744,     0.19744,     0.19744,     0.19744,     0.19744,     0.19744,     0.19478,     0.19478,     0.19478,     0.19478,     0.19478,     0.19478,     0.19478,     0.19478,     0.19416,     0.19416,     0.18367,     0.18367,     0.18367,     0.18367,     0.18367,     0.18367,
            0.18367,     0.18323,     0.18323,     0.18168,     0.18168,     0.18128,     0.18128,     0.18128,     0.18128,     0.18128,     0.18128,     0.17878,     0.17878,     0.17862,     0.17862,     0.17862,     0.17862,     0.17862,     0.17862,     0.17862,     0.17862,     0.17803,     0.17803,
            0.17409,     0.17409,     0.17351,     0.17351,     0.17351,     0.17351,       0.173,       0.173,     0.17228,     0.17228,     0.17034,     0.17034,     0.17034,     0.17034,     0.17034,     0.17034,     0.17034,     0.17034,     0.17034,     0.17034,     0.17034,     0.17034,      0.1699,
             0.1699,     0.16947,     0.16947,     0.16686,     0.16686,     0.16362,     0.16362,     0.16222,     0.16222,     0.16222,     0.16222,     0.16222,     0.16222,     0.16222,     0.16222,     0.16222,     0.16222,     0.16222,     0.16222,     0.16222,     0.16222,     0.16222,     0.16222,
            0.16222,     0.16222,     0.16222,     0.16222,     0.16222,     0.16222,     0.16222,     0.16222,     0.16222,     0.16222,     0.16222,     0.16222,     0.16222,     0.16044,     0.16044,     0.15873,     0.15873,     0.15753,     0.15753,     0.15735,     0.15735,     0.15735,     0.15735,
            0.15735,     0.15735,     0.15735,     0.15735,     0.15735,     0.15735,     0.15636,     0.15636,     0.15636,     0.15636,     0.15636,     0.15636,     0.15636,     0.15636,     0.15636,     0.15636,     0.15636,     0.15636,     0.15004,     0.15004,      0.1492,      0.1492,      0.1492,
             0.1492,      0.1492,      0.1492,      0.1492,      0.1492,      0.1492,      0.1492,     0.14424,     0.14424,     0.14331,     0.14331,     0.14141,     0.14141,     0.14141,     0.14141,     0.13566,     0.13566,     0.13348,     0.13348,     0.13348,     0.13348,     0.12926,     0.12926,
            0.12729,     0.12729,     0.12729,     0.12729,     0.12676,     0.12676,     0.12607,     0.12607,     0.12607,     0.12607,     0.12411,     0.12411,     0.12161,     0.12161,     0.11844,     0.11844,     0.11664,     0.11664,     0.11664,     0.11664,     0.11664,     0.11565,     0.11565,
            0.11274,     0.11274,     0.11274,     0.11274,     0.11242,     0.11242,     0.10944,     0.10944,     0.10944,     0.10944,     0.10944,     0.10944,     0.10572,     0.10572,     0.10499,     0.10499,     0.10481,     0.10481,     0.10311,     0.10311,     0.10311,     0.10311,    0.097948,
           0.097948,    0.097145,    0.097145,    0.095668,    0.095668,    0.095553,    0.095553,    0.095553,    0.095553,    0.095553,    0.095553,    0.095553,    0.095553,    0.095553,    0.095553,    0.093911,    0.093911,    0.093911,    0.093911,    0.092359,    0.092359,    0.091892,    0.091892,
           0.090393,    0.090393,    0.090393,    0.090393,    0.090105,    0.090105,    0.087856,    0.087856,    0.087089,    0.087089,    0.087089,    0.087089,    0.087089,    0.087089,     0.08694,     0.08694,    0.086531,    0.086531,    0.084119,    0.084119,    0.084119,    0.084119,    0.083723,

In [ ]:
BASE = "/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result"

model = RTDETR(f"{BASE}/train_imgsz768/weights/best.pt")
val  = model.val(data="/content/cadica_yolo/data.yaml", split="val",  imgsz=768)
test = model.val(data="/content/cadica_yolo/data.yaml", split="test", imgsz=768)
print(f"VAL  P={val.box.mp:.3f} R={val.box.mr:.3f} mAP50={val.box.map50:.3f} mAP50-95={val.box.map:.3f}")
print(f"TEST P={test.box.mp:.3f} R={test.box.mr:.3f} mAP50={test.box.map50:.3f} mAP50-95={test.box.map:.3f}")

Ultralytics 8.4.95 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
rt-detr-l summary: 310 layers, 31,985,795 parameters, 0 gradients, 103.4 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 54.7±13.0 MB/s, size: 96.0 KB)
val: Scanning /content/cadica_yolo/labels/val.cache... 335 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 335/335 93.7Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 1.2it/s 17.9s
                   all        335        506      0.165      0.281      0.102     0.0344
Speed: 3.2ms preprocess, 45.3ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to /content/runs/detect/val-3
Ultralytics 8.4.95 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
rt-detr-l summary: 310 layers, 31,985,795 parameters, 0 gradients, 103.4 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 57.3±7.3 MB/s, size: 98.1 KB)
val: Scanning /content/cadica_yolo/labels/test.cache... 273 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 273/273 88.1Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 1.2it/s 14.7s
                   all        273        273      0.418      0.242      0.221     0.0964
Speed: 3.2ms preprocess, 45.8ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to /content/runs/detect/val-4
VAL  P=0.165 R=0.281 mAP50=0.102 mAP50-95=0.034
TEST P=0.418 R=0.242 mAP50=0.221 mAP50-95=0.096

In [ ]:
# @title RCA/LCA 분리학습

# @title 1. LCA/RCA 데이터셋 분리
import os, re
from collections import defaultdict
from pathlib import Path
import pandas as pd

SRC_ROOT = Path("/content/cadica_yolo")
SPLIT_CSV = Path("/content/drive/MyDrive/🐥new_2_project/04_DL_project/08_전처리/common_split.csv")
VIEW_ROOTS = {"LCA": Path("/content/cadica_yolo_lca"), "RCA": Path("/content/cadica_yolo_rca")}
SPLITS = ["train", "val", "test"]
FRAME_PREFIX_RE = re.compile(r"^(p\d+)_(v\d+)_")

def load_view_map(split_csv=SPLIT_CSV):
    df = pd.read_csv(split_csv)
    return {(r.patient_id, r.video_id): r.view for r in df.itertuples()}

def get_view(filename, view_map):
    m = FRAME_PREFIX_RE.match(filename)
    if not m:
        return None
    return view_map.get((m.group(1), m.group(2)))

def build_view_datasets(src_root=SRC_ROOT, split_csv=SPLIT_CSV):
    view_map = load_view_map(split_csv)
    counts = defaultdict(lambda: defaultdict(int))
    unmatched = []

    for split in SPLITS:
        img_dir, lbl_dir = src_root / "images" / split, src_root / "labels" / split
        if not img_dir.exists():
            continue
        for img_path in sorted(img_dir.iterdir()):
            if not img_path.is_file():
                continue
            view = get_view(img_path.name, view_map)
            if view not in VIEW_ROOTS:
                unmatched.append(img_path.name)
                continue
            dst_root = VIEW_ROOTS[view]
            dst_img_dir, dst_lbl_dir = dst_root / "images" / split, dst_root / "labels" / split
            dst_img_dir.mkdir(parents=True, exist_ok=True)
            dst_lbl_dir.mkdir(parents=True, exist_ok=True)

            dst_img = dst_img_dir / img_path.name
            if not dst_img.exists():
                os.symlink(img_path.resolve(), dst_img)

            lbl_path = lbl_dir / f"{img_path.stem}.txt"
            dst_lbl = dst_lbl_dir / lbl_path.name
            if lbl_path.exists() and not dst_lbl.exists():
                os.symlink(lbl_path.resolve(), dst_lbl)

            counts[view][split] += 1

    for view, root in VIEW_ROOTS.items():
        (root / "data.yaml").write_text(
            f"path: {root}\ntrain: images/train\nval: images/val\ntest: images/test\n"
            "nc: 1\nnames: ['lesion']\n"
        )

    print("=== LCA / RCA 분리 결과 (bbox frame 수) ===")
    for view in VIEW_ROOTS:
        row = counts[view]
        print(f"{view}: train={row.get('train',0)} val={row.get('val',0)} "
              f"test={row.get('test',0)}  total={sum(row.values())}")
    if unmatched:
        print(f"[주의] view 매칭 실패 {len(unmatched)}개, 예: {unmatched[:5]}")
    return counts

build_view_datasets()

=== LCA / RCA 분리 결과 (bbox frame 수) ===
LCA: train=1818 val=254 test=153  total=2225
RCA: train=1259 val=81 test=120  total=1460

defaultdict(<function __main__.build_view_datasets.<locals>.<lambda>()>,
            {'LCA': defaultdict(int, {'train': 1818, 'val': 254, 'test': 153}),
             'RCA': defaultdict(int, {'train': 1259, 'val': 81, 'test': 120})})

In [ ]:
# @title 2-1. LCA 학습
from ultralytics import RTDETR

BASE = "/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result"

model_lca = RTDETR("rtdetr-l.pt")   # 원본 pretrained에서 새로 시작 (통합 학습 편향 방지)
model_lca.train(
    data="/content/cadica_yolo_lca/data.yaml",
    name="train_lca_v1",
    project=BASE,
    epochs=50, imgsz=640, batch=8,
    lr0=0.0005, optimizer="AdamW", amp=True, patience=20,
)

Ultralytics 8.4.95 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/cadica_yolo_lca/data.yaml, degrees=0.0, deterministic=True, device=, dfl=1.5, dis=6.0, distill_model=None, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.0005, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=rtdetr-l.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=train_lca_v1, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_lca_v1, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1
WARNING ⚠️ no model scale passed. Assuming scale='l'.

                   from  n    params  module                                       arguments
  0                  -1  1     25248  ultralytics.nn.modules.block.HGStem          [3, 32, 48]
  1                  -1  6    155072  ultralytics.nn.modules.block.HGBlock         [48, 48, 128, 3, 6]
  2                  -1  1      1408  ultralytics.nn.modules.conv.DWConv           [128, 128, 3, 2, 1, False]
  3                  -1  6    839296  ultralytics.nn.modules.block.HGBlock         [128, 96, 512, 3, 6]
  4                  -1  1      5632  ultralytics.nn.modules.conv.DWConv           [512, 512, 3, 2, 1, False]
  5                  -1  6   1695360  ultralytics.nn.modules.block.HGBlock         [512, 192, 1024, 5, 6, True, False]
  6                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  7                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  8                  -1  1     11264  ultralytics.nn.modules.conv.DWConv           [1024, 1024, 3, 2, 1, False]
  9                  -1  6   6708480  ultralytics.nn.modules.block.HGBlock         [1024, 384, 2048, 5, 6, True, False]
 10                  -1  1    524800  ultralytics.nn.modules.conv.Conv             [2048, 256, 1, 1, None, 1, 1, False]
 11                  -1  1    789760  ultralytics.nn.modules.transformer.AIFI      [256, 1024, 8]
 12                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14                   7  1    262656  ultralytics.nn.modules.conv.Conv             [1024, 256, 1, 1, None, 1, 1, False]
 15            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 17                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 18                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 19                   3  1    131584  ultralytics.nn.modules.conv.Conv             [512, 256, 1, 1, None, 1, 1, False]
 20            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 22                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 23            [-1, 17]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 24                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 25                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 26            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 27                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 28        [21, 24, 27]  1   7303907  ultralytics.nn.modules.head.RTDETRDecoder    [1, [256, 256, 256]]
rt-detr-l summary: 465 layers, 32,808,131 parameters, 32,808,131 gradients, 108.0 GFLOPs

Transferred 926/941 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 50.3±15.7 MB/s, size: 96.4 KB)
train: Scanning /content/cadica_yolo_lca/labels/train... 1818 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1818/1818 894.0it/s 2.0s
train: New cache created: /content/cadica_yolo_lca/labels/train.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 125.6±141.4 MB/s, size: 102.7 KB)
val: Scanning /content/cadica_yolo_lca/labels/val... 254 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 254/254 519.7it/s 0.5s
val: New cache created: /content/cadica_yolo_lca/labels/val.cache
optimizer: AdamW(lr=0.0005, momentum=0.937) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.0005), 226 bias(decay=0.0)
Plotting labels to /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_lca_v1/labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_lca_v1
Starting training for 50 epochs...

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       1/50      6.46G      2.318      3.376     0.7754         42        640: 0% ──────────── 0/228  7.0s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       1/50      6.53G      1.521     0.7824     0.5082         12        640: 100% ━━━━━━━━━━━━ 228/228 1.4it/s 2:45
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 1.5it/s 10.9s
                   all        254        425    0.00433      0.325    0.00296   0.000515

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       2/50      6.53G      1.573     0.4029     0.3778         19        640: 0% ──────────── 0/228  0.9s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       2/50      6.53G      1.047     0.7999     0.2711          5        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:32
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 2.8it/s 5.7s
                   all        254        425      0.024       0.24     0.0202    0.00509

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       3/50      6.53G     0.7079      1.266     0.1822          8        640: 0% ──────────── 0/228  1.0s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       3/50      6.53G     0.6911      1.058     0.1594          3        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:31
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 2.8it/s 5.6s
                   all        254        425     0.0351      0.221     0.0165    0.00483

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       4/50      6.53G     0.5748      1.069     0.1105         23        640: 0% ──────────── 0/228  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       4/50      6.53G     0.5864      1.114     0.1291          2        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:32
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 2.6it/s 6.2s
                   all        254        425     0.0294      0.186     0.0184    0.00584

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       5/50      6.53G     0.6329      1.013     0.1551         14        640: 0% ──────────── 0/228  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       5/50      6.53G     0.5594      1.085     0.1269          6        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:34
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 2.7it/s 6.0s
                   all        254        425     0.0543      0.127     0.0236    0.00717

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       6/50      6.53G     0.5496      1.031     0.1401         16        640: 0% ──────────── 0/228  1.1s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       6/50      6.53G     0.5392      1.017     0.1223          4        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:32
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 3.0it/s 5.3s
                   all        254        425     0.0461      0.162     0.0256    0.00928

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       7/50      6.53G     0.5815      0.942     0.1118         20        640: 0% ──────────── 0/228  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       7/50      6.53G     0.6162     0.8014     0.1482          1        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:29
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 2.7it/s 5.9s
                   all        254        425      0.107      0.165     0.0438     0.0108

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       8/50      6.53G     0.6944     0.6683     0.2114         18        640: 0% ──────────── 0/228  1.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       8/50      6.53G     0.6727     0.6681     0.1646          3        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:31
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 2.9it/s 5.6s
                   all        254        425      0.224      0.141     0.0744     0.0181

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       9/50      6.53G     0.5329     0.6917     0.1406         19        640: 0% ──────────── 0/228  1.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       9/50      6.53G     0.6365     0.6414     0.1552          3        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:33
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 3.1it/s 5.2s
                   all        254        425      0.259      0.148     0.0797     0.0221

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      10/50      6.53G     0.6516     0.5886     0.1232         25        640: 0% ──────────── 0/228  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      10/50      6.53G     0.6195      0.615     0.1519          6        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:32
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 2.8it/s 5.7s
                   all        254        425      0.184      0.202     0.0578     0.0149

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      11/50      6.53G     0.6708     0.5032     0.1566         16        640: 0% ──────────── 0/228  0.8s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      11/50      6.53G     0.6035     0.6005     0.1427          9        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:33
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 3.0it/s 5.3s
                   all        254        425      0.204      0.176       0.09     0.0399

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      12/50      6.53G     0.9409     0.5143     0.2273         17        640: 0% ──────────── 0/228  1.0s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      12/50      6.53G     0.5986      0.631      0.141          0        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:32
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 2.8it/s 5.6s
                   all        254        425      0.137     0.0965     0.0324    0.00783

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      13/50      6.53G     0.4521     0.6748    0.08589         28        640: 0% ──────────── 0/228  1.2s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      13/50      6.53G     0.5738     0.5652     0.1378          9        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:33
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 3.0it/s 5.3s
                   all        254        425      0.198      0.148     0.0919     0.0281

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      14/50      6.53G     0.5453     0.4991     0.1723         15        640: 0% ──────────── 0/228  1.1s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      14/50      6.53G     0.5536     0.5396     0.1297          4        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:32
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 2.7it/s 5.9s
                   all        254        425      0.179      0.118     0.0555     0.0132

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      15/50      6.53G        0.4     0.4873     0.1185         14        640: 0% ──────────── 0/228  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      15/50      6.53G     0.5464     0.5645     0.1284          8        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:32
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 2.8it/s 5.7s
                   all        254        425      0.134      0.118     0.0536     0.0132

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      16/50      6.53G     0.5633     0.5549     0.1085         25        640: 0% ──────────── 0/228  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      16/50      6.53G     0.5467     0.5325     0.1272          2        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:30
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 2.7it/s 5.9s
                   all        254        425      0.179      0.108      0.047     0.0157

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      17/50      6.53G     0.4376      0.511    0.09075         29        640: 0% ──────────── 0/228  1.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      17/50      6.53G     0.5235     0.5465       0.12          4        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:33
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 3.0it/s 5.3s
                   all        254        425      0.168      0.127     0.0487     0.0132

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      18/50      6.53G      0.548      0.512     0.1169         24        640: 0% ──────────── 0/228  0.8s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      18/50      6.53G     0.5176     0.5122     0.1191          3        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:32
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 2.9it/s 5.6s
                   all        254        425      0.166      0.118      0.058     0.0126

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      19/50      6.53G     0.5795     0.4892     0.0866         26        640: 0% ──────────── 0/228  1.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      19/50      6.53G     0.5211     0.5159     0.1216          8        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:32
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 2.7it/s 6.0s
                   all        254        425      0.146      0.118     0.0559     0.0147

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      20/50      6.53G     0.3289     0.4054     0.1111         10        640: 0% ──────────── 0/228  1.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      20/50      6.53G     0.5122     0.5003     0.1182          9        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:32
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 2.7it/s 5.8s
                   all        254        425      0.156      0.165     0.0687     0.0148

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      21/50      6.53G     0.5919      0.683     0.1645         19        640: 0% ──────────── 0/228  1.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      21/50      6.53G     0.4948     0.5019     0.1128          5        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:32
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 2.8it/s 5.7s
                   all        254        425      0.174      0.137     0.0612     0.0139

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      22/50      6.53G     0.3326     0.4769    0.06613         16        640: 0% ──────────── 0/228  1.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      22/50      6.53G      0.497     0.4965     0.1137          8        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:32
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 2.6it/s 6.0s
                   all        254        425      0.227      0.113     0.0634     0.0144

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      23/50      6.53G     0.5344     0.4844     0.1345         18        640: 0% ──────────── 0/228  1.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      23/50      6.53G     0.4956     0.4871     0.1135          1        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:33
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 3.0it/s 5.3s
                   all        254        425      0.171      0.113      0.056     0.0154

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      24/50      6.53G     0.4162     0.4089     0.0727         15        640: 0% ──────────── 0/228  1.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      24/50      6.53G     0.4781     0.4776     0.1079          2        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:33
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 2.7it/s 5.9s
                   all        254        425       0.18      0.169     0.0606     0.0141

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      25/50      6.53G     0.3961     0.4513    0.08744         18        640: 0% ──────────── 0/228  1.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      25/50      6.53G     0.4704     0.4808     0.1074          6        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:33
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 2.7it/s 5.8s
                   all        254        425      0.201      0.139     0.0531     0.0124

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      26/50      6.53G     0.4702     0.5428     0.1146         17        640: 0% ──────────── 0/228  1.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      26/50      6.53G      0.452     0.4688     0.1014          6        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:32
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 3.0it/s 5.3s
                   all        254        425      0.251      0.129      0.102     0.0263

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      27/50      6.53G     0.4278     0.5188    0.09155         21        640: 0% ──────────── 0/228  1.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      27/50      6.53G     0.4556     0.4603     0.1009         12        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:33
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 2.9it/s 5.5s
                   all        254        425      0.195      0.113     0.0569      0.013

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      28/50      6.53G     0.5078     0.4077    0.08728         25        640: 0% ──────────── 0/228  1.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      28/50      6.53G     0.4583     0.4644     0.1022         10        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:33
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 2.6it/s 6.1s
                   all        254        425      0.201      0.118     0.0591     0.0133

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      29/50      6.53G     0.3584     0.4816    0.09468         13        640: 0% ──────────── 0/228  1.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      29/50      6.53G     0.4459     0.4512    0.09682          9        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:33
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 2.7it/s 6.0s
                   all        254        425      0.223      0.101     0.0557     0.0117

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      30/50      6.53G     0.4875     0.5232    0.09748         22        640: 0% ──────────── 0/228  1.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      30/50      6.53G     0.4444     0.4535    0.09768          4        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:32
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 3.0it/s 5.3s
                   all        254        425      0.253      0.122     0.0805     0.0229

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      31/50      6.53G     0.5518     0.5167     0.1461         23        640: 0% ──────────── 0/228  1.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      31/50      6.53G     0.4387     0.4534    0.09589          3        640: 100% ━━━━━━━━━━━━ 228/228 1.5it/s 2:33
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 2.6it/s 6.0s
                   all        254        425      0.184      0.127     0.0702     0.0162
EarlyStopping: Training stopped early as no improvement observed in last 20 epochs. Best results observed at epoch 11, best model saved as best.pt.
To update EarlyStopping(patience=20) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

31 epochs completed in 1.898 hours.
Optimizer stripped from /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_lca_v1/weights/last.pt, 66.3MB
Optimizer stripped from /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_lca_v1/weights/best.pt, 66.3MB

Validating /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_lca_v1/weights/best.pt...
Ultralytics 8.4.95 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)

In [ ]:
from ultralytics import RTDETR
BASE = "/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result"
model = RTDETR(f"{BASE}/train_lca_v1/weights/best.pt")
val  = model.val(data="/content/cadica_yolo_lca/data.yaml", split="val",  imgsz=640)
test = model.val(data="/content/cadica_yolo_lca/data.yaml", split="test", imgsz=640)
print(f"LCA VAL  P={val.box.mp:.3f} R={val.box.mr:.3f} mAP50={val.box.map50:.3f} mAP50-95={val.box.map:.3f}")
print(f"LCA TEST P={test.box.mp:.3f} R={test.box.mr:.3f} mAP50={test.box.map50:.3f} mAP50-95={test.box.map:.3f}")

Ultralytics 8.4.95 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
rt-detr-l summary: 310 layers, 31,985,795 parameters, 0 gradients, 103.4 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 61.8±19.0 MB/s, size: 100.2 KB)
val: Scanning /content/cadica_yolo_lca/labels/val.cache... 254 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 254/254 41.0Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 16/16 1.6it/s 9.9s
                   all        254        425      0.209      0.182     0.0922     0.0404
Speed: 2.2ms preprocess, 32.6ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to /content/runs/detect/val-5
Ultralytics 8.4.95 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
rt-detr-l summary: 310 layers, 31,985,795 parameters, 0 gradients, 103.4 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 50.8±9.1 MB/s, size: 101.4 KB)
val: Scanning /content/cadica_yolo_lca/labels/test... 153 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 153/153 811.5it/s 0.2s
val: New cache created: /content/cadica_yolo_lca/labels/test.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 1.6it/s 6.3s
                   all        153        153      0.813      0.431      0.463      0.184
Speed: 3.7ms preprocess, 32.9ms inference, 0.0ms loss, 0.1ms postprocess per image
Results saved to /content/runs/detect/val-6
LCA VAL  P=0.209 R=0.182 mAP50=0.092 mAP50-95=0.040
LCA TEST P=0.813 R=0.431 mAP50=0.463 mAP50-95=0.184

In [ ]:
from ultralytics import RTDETR
BASE = "/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result"

# 통합 baseline → LCA test
base = RTDETR(f"{BASE}/train_v3_amp_on/weights/best.pt")
base_lca = base.val(data="/content/cadica_yolo_lca/data.yaml", split="test", imgsz=640)
print(f"BASELINE on LCA-TEST  P={base_lca.box.mp:.3f} R={base_lca.box.mr:.3f} "
      f"mAP50={base_lca.box.map50:.3f} mAP50-95={base_lca.box.map:.3f}")

Ultralytics 8.4.95 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
rt-detr-l summary: 310 layers, 31,985,795 parameters, 0 gradients, 103.4 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1990.5±471.2 MB/s, size: 106.9 KB)
val: Scanning /content/cadica_yolo_lca/labels/test.cache... 153 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 153/153 42.8Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 1.5it/s 6.6s
                   all        153        153      0.739      0.463      0.485      0.242
Speed: 2.8ms preprocess, 34.8ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to /content/runs/detect/val-7
BASELINE on LCA-TEST  P=0.739 R=0.463 mAP50=0.485 mAP50-95=0.242

In [ ]:
# @title RCA 학습
from ultralytics import RTDETR

BASE = "/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result"

model_rca = RTDETR("rtdetr-l.pt")  # 원본 pretrained에서 새로 시작
model_rca.train(
    data="/content/cadica_yolo_rca/data.yaml",
    name="train_rca_v1",
    project=BASE,
    epochs=50,
    imgsz=640,
    batch=8,
    lr0=0.0005,
    optimizer="AdamW",
    amp=True,
    patience=20,
)

Ultralytics 8.4.95 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/cadica_yolo_rca/data.yaml, degrees=0.0, deterministic=True, device=, dfl=1.5, dis=6.0, distill_model=None, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.0005, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=rtdetr-l.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=train_rca_v1, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_rca_v1, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1
WARNING ⚠️ no model scale passed. Assuming scale='l'.

                   from  n    params  module                                       arguments
  0                  -1  1     25248  ultralytics.nn.modules.block.HGStem          [3, 32, 48]
  1                  -1  6    155072  ultralytics.nn.modules.block.HGBlock         [48, 48, 128, 3, 6]
  2                  -1  1      1408  ultralytics.nn.modules.conv.DWConv           [128, 128, 3, 2, 1, False]
  3                  -1  6    839296  ultralytics.nn.modules.block.HGBlock         [128, 96, 512, 3, 6]
  4                  -1  1      5632  ultralytics.nn.modules.conv.DWConv           [512, 512, 3, 2, 1, False]
  5                  -1  6   1695360  ultralytics.nn.modules.block.HGBlock         [512, 192, 1024, 5, 6, True, False]
  6                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  7                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  8                  -1  1     11264  ultralytics.nn.modules.conv.DWConv           [1024, 1024, 3, 2, 1, False]
  9                  -1  6   6708480  ultralytics.nn.modules.block.HGBlock         [1024, 384, 2048, 5, 6, True, False]
 10                  -1  1    524800  ultralytics.nn.modules.conv.Conv             [2048, 256, 1, 1, None, 1, 1, False]
 11                  -1  1    789760  ultralytics.nn.modules.transformer.AIFI      [256, 1024, 8]
 12                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14                   7  1    262656  ultralytics.nn.modules.conv.Conv             [1024, 256, 1, 1, None, 1, 1, False]
 15            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 17                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 18                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 19                   3  1    131584  ultralytics.nn.modules.conv.Conv             [512, 256, 1, 1, None, 1, 1, False]
 20            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 22                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 23            [-1, 17]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 24                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 25                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 26            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 27                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 28        [21, 24, 27]  1   7303907  ultralytics.nn.modules.head.RTDETRDecoder    [1, [256, 256, 256]]
rt-detr-l summary: 465 layers, 32,808,131 parameters, 32,808,131 gradients, 108.0 GFLOPs

Transferred 926/941 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 55.9±10.0 MB/s, size: 93.2 KB)
train: Scanning /content/cadica_yolo_rca/labels/train... 1259 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1259/1259 843.5it/s 1.5s
train: New cache created: /content/cadica_yolo_rca/labels/train.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
WARNING ⚠️ val: Slow image access detected (ping: 0.0±0.0 ms, read: 37.0±15.6 MB/s, size: 99.6 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
val: Scanning /content/cadica_yolo_rca/labels/val... 81 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 81/81 452.8it/s 0.2s
val: New cache created: /content/cadica_yolo_rca/labels/val.cache
optimizer: AdamW(lr=0.0005, momentum=0.937) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.0005), 226 bias(decay=0.0)
Plotting labels to /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_rca_v1/labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_rca_v1
Starting training for 50 epochs...

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       1/50      6.46G      1.827      7.846     0.5606         19        640: 0% ──────────── 0/158  6.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       1/50      6.71G      1.384     0.9552     0.4513          9        640: 100% ━━━━━━━━━━━━ 158/158 1.3it/s 1:57
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 1.0s/it 6.2s
                   all         81         81    0.00214      0.642    0.00412   0.000901

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       2/50      6.71G     0.9553     0.9054     0.2473         13        640: 0% ──────────── 0/158  0.9s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       2/50      6.72G      0.914     0.9227      0.224          9        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:44
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.4it/s 1.8s
                   all         81         81     0.0148      0.519     0.0499     0.0119

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       3/50      6.72G     0.9855     0.9848     0.3005         14        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       3/50      6.72G     0.7234      1.092     0.1718          5        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:47
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.8it/s 2.1s
                   all         81         81     0.0176      0.395     0.0612     0.0226

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       4/50      6.72G     0.5604      1.123    0.09276         26        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       4/50      6.72G     0.6051       1.15      0.141          7        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:48
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.9it/s 2.1s
                   all         81         81      0.025      0.198     0.0327     0.0111

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       5/50      6.72G     0.6198      1.089     0.1675         19        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       5/50      6.72G     0.5824      1.115     0.1356          7        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:45
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.4it/s 1.8s
                   all         81         81     0.0165       0.37      0.011     0.0041

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       6/50      6.72G     0.6122     0.9619     0.1409         28        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       6/50      6.72G     0.5554      1.078      0.128         11        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:44
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.0it/s 2.0s
                   all         81         81      0.037      0.333     0.0283     0.0115

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       7/50      6.72G     0.6934      0.949     0.1698         25        640: 0% ──────────── 0/158  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       7/50      6.72G      0.557       1.03     0.1322          4        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:44
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.4it/s 1.8s
                   all         81         81     0.0241      0.247     0.0184    0.00564

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       8/50      6.72G     0.3927      1.169     0.1116         16        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       8/50      6.72G     0.5676       0.95      0.136          4        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:43
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.1it/s 1.9s
                   all         81         81      0.187       0.17      0.086     0.0235

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       9/50      6.72G     0.6289     0.9326     0.1216         20        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       9/50      6.72G     0.6392     0.6305     0.1595          6        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:48
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.4it/s 1.8s
                   all         81         81      0.269      0.247      0.181     0.0638

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      10/50      6.72G     0.6487     0.5242      0.141         21        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      10/50      6.72G     0.6612     0.5741       0.17          3        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:48
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.9it/s 2.1s
                   all         81         81      0.155      0.185     0.0647     0.0116

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      11/50      6.72G     0.5863     0.7396       0.14         16        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      11/50      6.72G     0.6482     0.5783     0.1635         10        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:45
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.4it/s 1.8s
                   all         81         81      0.134      0.123     0.0353    0.00858

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      12/50      6.72G     0.6986     0.6196     0.1755         19        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      12/50      6.72G     0.6441     0.5314     0.1656          8        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:45
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.0it/s 2.0s
                   all         81         81      0.314      0.309      0.163     0.0334

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      13/50      6.72G     0.6713     0.4487     0.1585         19        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      13/50      6.72G     0.6229      0.518     0.1566          5        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:44
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.4it/s 1.8s
                   all         81         81       0.16      0.198     0.0571     0.0127

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      14/50      6.72G     0.7069     0.4869      0.197         20        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      14/50      6.72G     0.5923     0.5193     0.1489          7        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:47
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.0it/s 2.0s
                   all         81         81      0.258      0.235      0.118     0.0332

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      15/50      6.72G     0.4497      0.461    0.09394         14        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      15/50      6.72G      0.585      0.528     0.1404          6        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:45
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.4it/s 1.8s
                   all         81         81      0.193      0.185     0.0638     0.0123

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      16/50      6.72G     0.5103     0.5222     0.1588         17        640: 0% ──────────── 0/158  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      16/50      6.72G     0.5709     0.4976     0.1388         10        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:45
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.8it/s 2.2s
                   all         81         81      0.343      0.333      0.224     0.0487

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      17/50      6.72G     0.6015     0.4684     0.1978         16        640: 0% ──────────── 0/158  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      17/50      6.72G     0.5745     0.4951     0.1392          6        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:45
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.4it/s 1.8s
                   all         81         81      0.306      0.272      0.163     0.0433

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      18/50      6.72G     0.5846     0.4445     0.1576         17        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      18/50      6.72G     0.5618     0.4991     0.1376          4        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:45
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.0it/s 2.0s
                   all         81         81      0.382      0.321       0.23     0.0565

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      19/50      6.72G     0.7324     0.4815     0.1892         16        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      19/50      6.72G     0.5759      0.509     0.1392          6        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:44
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.4it/s 1.8s
                   all         81         81      0.213      0.198      0.107     0.0243

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      20/50      6.72G     0.5696     0.5926     0.1912         18        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      20/50      6.72G     0.5561     0.5144     0.1364          8        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:45
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.0it/s 2.0s
                   all         81         81        0.2       0.21     0.0877     0.0211

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      21/50      6.72G     0.6487      0.428     0.1837         17        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      21/50      6.72G     0.5501     0.4817     0.1325          6        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:44
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.4it/s 1.7s
                   all         81         81      0.503      0.296      0.253     0.0676

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      22/50      6.72G        0.5     0.4382    0.09883         21        640: 0% ──────────── 0/158  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      22/50      6.72G     0.5415     0.4674     0.1312          4        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:49
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.4it/s 1.8s
                   all         81         81      0.129      0.136     0.0544     0.0115

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      23/50      6.72G     0.5526     0.4334     0.1406         19        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      23/50      6.72G     0.5347     0.4604     0.1277          3        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:44
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.0it/s 2.0s
                   all         81         81      0.302      0.214      0.172     0.0461

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      24/50      6.72G     0.4175     0.5121    0.09316         14        640: 0% ──────────── 0/158  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      24/50      6.72G     0.5269     0.4628     0.1291          4        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:46
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.4it/s 1.8s
                   all         81         81      0.242      0.136     0.0728     0.0135

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      25/50      6.72G     0.6962     0.3823     0.1407         18        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      25/50      6.72G     0.5176     0.4587     0.1231          8        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:44
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.3it/s 1.8s
                   all         81         81      0.337      0.357      0.245     0.0611

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      26/50      6.72G     0.6568     0.5029      0.132         20        640: 0% ──────────── 0/158  0.8s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      26/50      6.72G     0.5243     0.4559      0.126         12        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:45
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.4it/s 1.8s
                   all         81         81      0.237      0.185      0.112     0.0214

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      27/50      6.72G     0.6122     0.4747     0.1242         21        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      27/50      6.72G     0.5224     0.4646     0.1237          9        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:45
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.9it/s 2.1s
                   all         81         81      0.104      0.123     0.0275    0.00508

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      28/50      6.72G     0.5711     0.4682     0.1356         15        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      28/50      6.72G     0.4964     0.4626      0.119          9        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:45
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.5it/s 1.7s
                   all         81         81      0.538      0.222      0.185     0.0394

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      29/50      6.72G     0.6284     0.4192     0.1459         19        640: 0% ──────────── 0/158  0.8s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      29/50      6.72G     0.5045      0.467     0.1205          4        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:45
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.4it/s 1.8s
                   all         81         81      0.303      0.185     0.0854     0.0172

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      30/50      6.72G     0.5071     0.4193    0.08058         19        640: 0% ──────────── 0/158  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      30/50      6.72G     0.4899     0.4524     0.1162          7        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:44
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.4it/s 1.7s
                   all         81         81       0.12      0.123     0.0387    0.00861

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      31/50      6.72G      0.476     0.4252    0.09303         22        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      31/50      6.72G     0.4966     0.4523     0.1196          3        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:45
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.2it/s 1.9s
                   all         81         81       0.23      0.247      0.114     0.0302

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      32/50      6.72G     0.3662     0.4385     0.0947         11        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      32/50      6.72G     0.4995     0.4426     0.1176          8        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:45
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.9it/s 2.1s
                   all         81         81      0.216      0.222      0.111      0.026

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      33/50      6.72G     0.4657     0.4477    0.09348         16        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      33/50      6.72G     0.4745     0.4346     0.1127          4        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:45
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.4it/s 1.8s
                   all         81         81      0.268      0.213      0.135     0.0264

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      34/50      6.72G     0.4158     0.4561     0.1207         17        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      34/50      6.72G     0.4691     0.4315     0.1105          3        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:44
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.0it/s 2.0s
                   all         81         81      0.294      0.296      0.203     0.0429

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      35/50      6.72G     0.4857     0.4309      0.112         20        640: 0% ──────────── 0/158  0.8s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      35/50      6.72G     0.4682     0.4345       0.11          7        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:45
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.4it/s 1.8s
                   all         81         81      0.202      0.185     0.0936     0.0211

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      36/50      6.72G     0.4459     0.4892     0.0895         29        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      36/50      6.72G     0.4614     0.4321     0.1077          9        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:45
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.9it/s 2.0s
                   all         81         81      0.196      0.185      0.114     0.0195

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      37/50      6.72G     0.5334     0.4271     0.1152         21        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      37/50      6.72G     0.4417     0.4305     0.1005          6        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:45
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.4it/s 1.8s
                   all         81         81       0.16      0.185     0.0815     0.0245

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      38/50      6.72G     0.3976     0.3662     0.0775         26        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      38/50      6.72G     0.4428     0.4257     0.1025          8        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:45
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.0it/s 2.0s
                   all         81         81      0.217      0.247       0.11       0.03

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      39/50      6.72G     0.4846     0.4276    0.09925         15        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      39/50      6.72G     0.4363     0.4216      0.099          2        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:45
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.4it/s 1.8s
                   all         81         81      0.131      0.148       0.06     0.0166

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      40/50      6.72G     0.3818     0.3569     0.0716         14        640: 0% ──────────── 0/158  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      40/50      6.72G     0.4393     0.4217     0.1023         10        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:45
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.9it/s 2.0s
                   all         81         81      0.286      0.309      0.188     0.0473
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      41/50      6.72G     0.3875     0.4118     0.1093         13        640: 0% ──────────── 0/158  1.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      41/50      6.72G     0.3897     0.3995     0.1072          6        640: 100% ━━━━━━━━━━━━ 158/158 1.5it/s 1:44
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.4it/s 1.8s
                   all         81         81      0.364      0.148     0.0939     0.0223
EarlyStopping: Training stopped early as no improvement observed in last 20 epochs. Best results observed at epoch 21, best model saved as best.pt.
To update EarlyStopping(patience=20) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

41 epochs completed in 1.253 hours.
Optimizer stripped from /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_rca_v1/weights/last.pt, 66.3MB
Optimizer stripped from /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_rca_v1/weights/best.pt, 66.3MB

Validating /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_rca_v1/weights/best.pt...
Ultralytics 8.4.95 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
rt-detr-l summary: 310 layers, 31,985,795 parameters, 0 gradients, 103.4 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.2it/s 2.7s
                   all         81         81      0.559      0.259      0.243     0.0641
Speed: 0.7ms preprocess, 24.9ms inference, 0.0ms loss, 0.7ms postprocess per image
Results saved to /content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result/train_rca_v1

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x7f0a96ca7620>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,     0.71429,     0.71429,     0.71429,     0.71429,
            0.71429,     0.71429,     0.71429,     0.71429,     0.71429,     0.71429,     0.71429,     0.71429,     0.71429,     0.70588,     0.70588,     0.70588,     0.70588,     0.70588,     0.70588,     0.70588,     0.70588,     0.70588,     0.70588,     0.70588,     0.70588,     0.70588,     0.70588,
            0.70588,     0.70588,     0.70588,     0.70588,     0.70588,     0.70588,     0.70588,     0.70588,     0.70588,     0.70588,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,
            0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,
            0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,
            0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.65517,
            0.65517,     0.65517,     0.65517,     0.65517,     0.65517,     0.64516,     0.64516,     0.64516,     0.64516,     0.64516,     0.64516,     0.64516,     0.64516,     0.64516,     0.64516,     0.64516,     0.64516,     0.58333,     0.58333,     0.58333,     0.58333,     0.58333,     0.58333,
            0.58333,     0.58333,     0.58333,     0.58333,     0.58333,     0.58333,     0.56098,     0.56098,     0.56098,     0.56098,     0.56098,     0.56098,     0.56098,     0.56098,     0.56098,     0.56098,     0.56098,     0.56098,     0.56098,     0.56098,     0.56098,     0.56098,     0.56098,
            0.56098,     0.56098,     0.56098,     0.56098,     0.56098,     0.56098,     0.56098,     0.56098,     0.43103,     0.43103,     0.43103,     0.43103,     0.43103,     0.43103,     0.43103,     0.43103,     0.43103,     0.43103,     0.43103,     0.43103,     0.43103,     0.43103,     0.43103,
            0.43103,     0.43103,     0.43103,     0.43103,     0.43103,     0.43103,     0.43103,     0.43103,     0.43103,     0.43103,     0.28889,     0.28889,     0.28889,     0.28889,     0.28889,     0.28889,     0.28889,     0.28889,     0.28889,     0.28889,     0.28889,     0.28889,    0.018754,
           0.018754,    0.018754,    0.018754,    0.018754,    0.018754,    0.018754,    0.018754,    0.018754,    0.018754,    0.018754,    0.018754,    0.018754,    0.018754,    0.018754,    0.018754,    0.018754,    0.018754,    0.018754,    0.018754,    0.018754,    0.018754,    0.018754,    0.018754,
           0.018754,    0.016174,    0.016174,    0.016174,    0.016174,    0.016174,    0.016174,    0.016174,    0.016174,    0.016174,    0.016174,    0.016174,    0.016174,    0.013501,    0.013501,    0.013501,    0.013501,    0.013501,    0.013501,    0.013501,    0.013501,    0.013501,    0.013501,
           0.013501,    0.013501,    0.012403,    0.012403,    0.012403,    0.012403,    0.012403,    0.012403,    0.012403,    0.012403,    0.012403,    0.012403,    0.012403,    0.012403,    0.012403,    0.012403,    0.012403,    0.012403,    0.012403,    0.012403,    0.012403,    0.012403,    0.012403,
           0.012403,    0.012403,    0.012403,    0.012403,    0.012044,    0.012044,    0.012044,    0.012044,    0.012044,    0.012044,    0.012044,    0.012044,    0.012044,    0.012044,    0.012044,    0.012044,    0.012044,    0.012044,    0.012044,    0.012044,    0.012044,    0.012044,    0.012044,
           0.012044,    0.012044,    0.012044,    0.012044,    0.012044,    0.012044,    0.011978,    0.011978,    0.011978,    0.011978,    0.011978,    0.011978,    0.011978,    0.011978,    0.011978,    0.011978,    0.011978,    0.011978,     0.01192,     0.01192,     0.01192,     0.01192,     0.01192,
            0.01192,     0.01192,     0.01192,     0.01192,     0.01192,     0.01192,     0.01192,     0.01192,     0.01192,     0.01192,     0.01192,     0.01192,     0.01192,     0.01192,     0.01192,     0.01192,     0.01192,     0.01192,     0.01192,     0.01192,    0.011427,    0.011427,    0.011427,

In [ ]:
# @title RCA 평가 + baseline 공정비교
from ultralytics import RTDETR

BASE = "/content/drive/MyDrive/🐥new_2_project/04_DL_project/RT-DETR_result"

rca = RTDETR(f"{BASE}/train_rca_v1/weights/best.pt")
val  = rca.val(data="/content/cadica_yolo_rca/data.yaml", split="val",  imgsz=640)
test = rca.val(data="/content/cadica_yolo_rca/data.yaml", split="test", imgsz=640)
print(f"RCA VAL  P={val.box.mp:.3f} R={val.box.mr:.3f} mAP50={val.box.map50:.3f} mAP50-95={val.box.map:.3f}")
print(f"RCA TEST P={test.box.mp:.3f} R={test.box.mr:.3f} mAP50={test.box.map50:.3f} mAP50-95={test.box.map:.3f}")

base = RTDETR(f"{BASE}/train_v3_amp_on/weights/best.pt")
base_rca = base.val(data="/content/cadica_yolo_rca/data.yaml", split="test", imgsz=640)
print(f"BASELINE on RCA-TEST P={base_rca.box.mp:.3f} R={base_rca.box.mr:.3f} "
      f"mAP50={base_rca.box.map50:.3f} mAP50-95={base_rca.box.map:.3f}")

Ultralytics 8.4.95 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
rt-detr-l summary: 310 layers, 31,985,795 parameters, 0 gradients, 103.4 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2610.9±884.9 MB/s, size: 100.0 KB)
val: Scanning /content/cadica_yolo_rca/labels/val.cache... 81 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 81/81 30.9Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 1.4it/s 4.2s
                   all         81         81      0.557      0.259      0.243     0.0644
Speed: 5.1ms preprocess, 39.0ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to /content/runs/detect/val-8
Ultralytics 8.4.95 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
rt-detr-l summary: 310 layers, 31,985,795 parameters, 0 gradients, 103.4 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 58.9±11.6 MB/s, size: 106.3 KB)
val: Scanning /content/cadica_yolo_rca/labels/test... 120 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 120/120 879.4it/s 0.1s
val: New cache created: /content/cadica_yolo_rca/labels/test.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 1.2it/s 6.7s
                   all        120        120     0.0733     0.0667     0.0132    0.00367
Speed: 7.6ms preprocess, 39.6ms inference, 0.0ms loss, 0.3ms postprocess per image
Results saved to /content/runs/detect/val-9
RCA VAL  P=0.557 R=0.259 mAP50=0.243 mAP50-95=0.064
RCA TEST P=0.073 R=0.067 mAP50=0.013 mAP50-95=0.004
Ultralytics 8.4.95 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
rt-detr-l summary: 310 layers, 31,985,795 parameters, 0 gradients, 103.4 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2115.1±260.1 MB/s, size: 104.4 KB)
val: Scanning /content/cadica_yolo_rca/labels/test.cache... 120 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 120/120 28.0Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 1.4it/s 5.9s
                   all        120        120      0.188      0.189     0.0602     0.0204
Speed: 4.0ms preprocess, 39.5ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to /content/runs/detect/val-10
BASELINE on RCA-TEST P=0.188 R=0.189 mAP50=0.060 mAP50-95=0.020